import { ref, C, N } from "./helpers.mjs";

export const topicsA = [
  {
    topicId: "topic-chapter-frame",
    title: "Chapter frame: four issues the chapter must cover",
    importance: "context",
    sourceSection: "Chapter intro",
    sourceRefs: ref([1], "This chapter addresses four issues: data communications, networks, the Internet, and protocols and standards."),
    learningObjectives: [
      "State the four issues the chapter addresses",
      "Place later sections on that roadmap",
    ],
    concepts: [
      {
        id: "concept-four-issues",
        title: "Four chapter pillars",
        meaning: "Data communications, networks, the Internet, protocols and standards.",
        explanation: {
          what: "The source explicitly organizes Chapter 1 around four sequential issues.",
          why: "Gives students a scaffold before dense definitions.",
          parts: ["data communications", "networks", "the Internet", "protocols and standards"],
          concrete: "Broad definition of data communications → networks as a highway → Internet as internetwork example → protocol vs standard.",
        },
        importance: "medium",
        whyExamRelevant: "Low direct exam value, high structural value for chapter coherence.",
        claimClass: C,
        sourceRefs: ref([1]),
        prerequisites: [],
        relatedConceptIds: ["concept-data-communications", "concept-network", "concept-internet-global", "concept-protocol-elements"],
        commonConfusionIds: [],
      },
    ],
    relationships: [
      {
        id: "rel-frame-sequence",
        from: "concept-four-issues",
        type: "precedes",
        to: "concept-data-communications",
        explanation: "Chapter introduces data communications first, then networks, Internet, protocols/standards.",
        claimClass: C,
        sourceRefs: ref([1]),
      },
    ],
    definitions: [],
    formulas: [],
    examples: [],
    comparisons: [],
    applications: [],
    confusions: [],
    exerciseSignals: [],
    prerequisites: [],
    dependents: [
      "topic-data-communication",
      "topic-networks-criteria",
      "topic-internet",
      "topic-protocols",
      "topic-standards",
    ],
    preservationRequirements: [
      "Open with the four-issue roadmap so later sections are not orphaned facts.",
    ],
    simplificationControl: {
      acceptable: ["Name the four issues in one short roadmap paragraph."],
      notAcceptable: ["Drop the roadmap and jump straight into Shannon-style formulas."],
    },
    evidenceQuality: "high",
    coverage: {
      definition: true,
      mechanism: false,
      relationships: true,
      examples: false,
      comparisons: false,
      formulas: false,
      confusions: false,
    },
    uncertainties: [],
  },
  {
    topicId: "topic-data-communication",
    title: "Data communications: definition, effectiveness, five components",
    importance: "core",
    sourceSection: "1.1 DATA COMMUNICATIONS",
    sourceRefs: ref([1, 2, 3], "Data communications are the exchange of data between two devices via some form of transmission medium."),
    learningObjectives: [
      "Define data communications and data",
      "List the four effectiveness characteristics including jitter",
      "Name and explain the five components",
      "Use the protocol analogy to explain why connection ≠ communication",
    ],
    concepts: [
      {
        id: "concept-data",
        title: "Data",
        meaning: "Information presented in whatever form is agreed upon by the parties creating and using the data.",
        explanation: {
          what: "Data is agreed-form information, not merely 'numbers'.",
          why: "Without an agreed form, bits cannot be interpreted.",
          concrete: "Text, numbers, pictures, audio, video are popular message forms.",
        },
        importance: "medium",
        whyExamRelevant: "Foundational term; appears in definitions and component lists.",
        claimClass: C,
        sourceRefs: ref([2], "The word data refers to information presented in whatever form is agreed upon by the parties creating and using the data."),
        prerequisites: [],
        relatedConceptIds: ["concept-data-communications", "concept-message"],
        commonConfusionIds: [],
      },
      {
        id: "concept-telecommunication",
        title: "Telecommunication",
        meaning: "Communication at a distance (telephony, telegraphy, television).",
        explanation: {
          what: "tele = Greek for 'far'; includes telephony, telegraphy, television.",
          why: "Separates remote communication from face-to-face local communication.",
        },
        importance: "low",
        whyExamRelevant: "Occasional vocabulary item; not a computation target.",
        claimClass: C,
        sourceRefs: ref([1, 2]),
        prerequisites: [],
        relatedConceptIds: ["concept-data-communications"],
        commonConfusionIds: [],
      },
      {
        id: "concept-data-communications",
        title: "Data communications",
        meaning: "Exchange of data between two devices via some form of transmission medium such as a wire cable.",
        explanation: {
          what: "Two-device exchange over a medium, requiring a hardware+software communication system.",
          why: "Defines the chapter's first pillar.",
          how: "Devices participate in a communication system made of hardware (physical equipment) and software (programs).",
          parts: ["sender device", "receiver device", "transmission medium", "communication system hardware/software"],
          notMeaning: "Not merely 'sending a file'; not the same as networking topology.",
        },
        importance: "high",
        whyExamRelevant: "Core definition; review Q1 builds on the five components of this system.",
        claimClass: C,
        sourceRefs: ref([2], "Data communications are the exchange of data between two devices via some form of transmission medium."),
        prerequisites: ["concept-data"],
        relatedConceptIds: ["concept-effectiveness", "concept-five-components"],
        commonConfusionIds: ["conf-network-vs-internet"],
      },
      {
        id: "concept-effectiveness",
        title: "Effectiveness characteristics",
        meaning: "Delivery, accuracy, timeliness, and jitter determine data-communications effectiveness.",
        explanation: {
          what: "Four fundamental characteristics of an effective system.",
          why: "Correct destination without accuracy or timing is still useless.",
          parts: ["delivery", "accuracy", "timeliness", "jitter"],
          whenChanges: "If any one fails, the communication is ineffective for real applications.",
        },
        importance: "high",
        whyExamRelevant: "Direct source emphasis; easy multiple-choice set.",
        claimClass: C,
        sourceRefs: ref([2], "The effectiveness of a data communications system depends on four fundamental characteristics: delivery, accuracy, timeliness, and jitter."),
        prerequisites: ["concept-data-communications"],
        relatedConceptIds: ["concept-jitter", "concept-realtime"],
        commonConfusionIds: [],
      },
      {
        id: "concept-delivery",
        title: "Delivery",
        meaning: "System must deliver data to the correct destination — intended device/user and only that one.",
        explanation: {
          what: "Correct-destination requirement.",
          why: "Misdelivery is a security and correctness failure.",
        },
        importance: "high",
        whyExamRelevant: "Part of the four-characteristic set.",
        claimClass: C,
        sourceRefs: ref([2]),
        prerequisites: ["concept-effectiveness"],
        relatedConceptIds: ["concept-accuracy"],
        commonConfusionIds: [],
      },
      {
        id: "concept-accuracy",
        title: "Accuracy",
        meaning: "System must deliver data accurately; altered-and-uncorrected data are unusable.",
        explanation: {
          what: "Integrity of bits in transit.",
          notMeaning: "Not the same as timeliness — late-but-correct is still a different failure mode.",
        },
        importance: "high",
        whyExamRelevant: "Part of the four-characteristic set.",
        claimClass: C,
        sourceRefs: ref([2]),
        prerequisites: ["concept-effectiveness"],
        relatedConceptIds: ["concept-delivery"],
        commonConfusionIds: [],
      },
      {
        id: "concept-timeliness",
        title: "Timeliness",
        meaning: "Data delivered late are useless; for audio/video this means real-time transmission.",
        explanation: {
          what: "On-time delivery; real-time = as produced, same order, without significant delay.",
          why: "Interactive media fail without timing even if bits are correct.",
        },
        importance: "high",
        whyExamRelevant: "Part of the four-characteristic set; links to jitter.",
        claimClass: C,
        sourceRefs: ref([2]),
        prerequisites: ["concept-effectiveness"],
        relatedConceptIds: ["concept-jitter", "concept-realtime"],
        commonConfusionIds: [],
      },
      {
        id: "concept-jitter",
        title: "Jitter",
        meaning: "Variation in packet arrival time — uneven delay in audio/video packet delivery.",
        explanation: {
          what: "Inconsistent inter-arrival times produce uneven quality.",
          why: "Constant average delay is not enough if delay varies packet-to-packet.",
          concrete: "Packets sent every 30 ms; some arrive with 30 ms delay, others 40 ms → uneven video.",
          notMeaning: "Not simply 'high delay'; it is delay variation.",
        },
        importance: "high",
        whyExamRelevant: "Explicitly defined with a numeric illustration; frequently dropped by summarizers.",
        claimClass: C,
        sourceRefs: ref([2], "Jitter refers to the variation in the packet arrival time."),
        prerequisites: ["concept-timeliness"],
        relatedConceptIds: ["concept-realtime"],
        commonConfusionIds: [],
      },
      {
        id: "concept-realtime",
        title: "Real-time transmission",
        meaning: "Timely delivery of audio/video as produced, in order, without significant delay.",
        explanation: {
          what: "Special case of timeliness for continuous media.",
          how: "Packets must keep production pace and ordering.",
        },
        importance: "medium",
        whyExamRelevant: "Often paired with jitter questions.",
        claimClass: C,
        sourceRefs: ref([2]),
        prerequisites: ["concept-timeliness"],
        relatedConceptIds: ["concept-jitter"],
        commonConfusionIds: [],
      },
      {
        id: "concept-five-components",
        title: "Five components of a data communications system",
        meaning: "Message, sender, receiver, transmission medium, protocol.",
        explanation: {
          what: "Complete component taxonomy (Figure 1.1).",
          why: "Protocol is a component — connection without rules does not communicate.",
          parts: ["message", "sender", "receiver", "transmission medium", "protocol"],
          concrete: "French speaker vs Japanese speaker: connected but not communicating without a shared protocol.",
        },
        importance: "high",
        whyExamRelevant: "Review Q1 asks students to identify the five components.",
        claimClass: C,
        sourceRefs: ref([2, 3], "A data communications system has five components."),
        prerequisites: ["concept-data-communications"],
        relatedConceptIds: ["concept-protocol-basic", "concept-message", "concept-sender", "concept-receiver", "concept-transmission-medium"],
        commonConfusionIds: [],
      },
      {
        id: "concept-message",
        title: "Message",
        meaning: "The information (data) to be communicated.",
        explanation: {
          what: "Payload of the communication.",
          parts: ["text", "numbers", "pictures", "audio", "video"],
        },
        importance: "high",
        whyExamRelevant: "Component #1 in the five-part taxonomy.",
        claimClass: C,
        sourceRefs: ref([2]),
        prerequisites: ["concept-five-components"],
        relatedConceptIds: ["concept-data"],
        commonConfusionIds: [],
      },
      {
        id: "concept-sender",
        title: "Sender",
        meaning: "Device that sends the data message.",
        explanation: {
          what: "Source endpoint.",
          concrete: "Computer, workstation, telephone handset, video camera.",
        },
        importance: "high",
        whyExamRelevant: "Component #2.",
        claimClass: C,
        sourceRefs: ref([2]),
        prerequisites: ["concept-five-components"],
        relatedConceptIds: ["concept-receiver"],
        commonConfusionIds: [],
      },
      {
        id: "concept-receiver",
        title: "Receiver",
        meaning: "Device that receives the message.",
        explanation: {
          what: "Destination endpoint.",
          concrete: "Computer, workstation, telephone handset, television.",
        },
        importance: "high",
        whyExamRelevant: "Component #3.",
        claimClass: C,
        sourceRefs: ref([2]),
        prerequisites: ["concept-five-components"],
        relatedConceptIds: ["concept-sender"],
        commonConfusionIds: [],
      },
      {
        id: "concept-transmission-medium",
        title: "Transmission medium",
        meaning: "Physical path by which a message travels from sender to receiver.",
        explanation: {
          what: "Physical channel.",
          concrete: "Twisted-pair wire, coaxial cable, fiber-optic cable, radio waves.",
          notMeaning: "Not the same as protocol; medium is the path, protocol is the ruleset.",
        },
        importance: "high",
        whyExamRelevant: "Component #4; media examples are common MCQs.",
        claimClass: C,
        sourceRefs: ref([2]),
        prerequisites: ["concept-five-components"],
        relatedConceptIds: ["concept-protocol-basic"],
        commonConfusionIds: [],
      },
      {
        id: "concept-protocol-basic",
        title: "Protocol (basic role in data communications)",
        meaning: "Set of rules that govern data communications; agreement between communicating devices.",
        explanation: {
          what: "Without a protocol, two devices may be connected but not communicating.",
          why: "Shared rules enable interpretation of bits.",
          concrete: "French speaker cannot understand a Japanese-only speaker.",
          notMeaning: "Not a physical device; it is a ruleset (component #5).",
        },
        importance: "high",
        whyExamRelevant: "Component #5; also the bridge to section 1.4.",
        claimClass: C,
        sourceRefs: ref([3], "A protocol is a set of rules that govern data communications."),
        prerequisites: ["concept-five-components"],
        relatedConceptIds: ["concept-protocol-elements"],
        commonConfusionIds: ["conf-protocol-standard"],
      },
    ],
    relationships: [
      {
        id: "rel-effectiveness-parts",
        from: "concept-effectiveness",
        type: "part-of",
        to: "concept-data-communications",
        explanation: "Effectiveness characteristics evaluate whether data communications succeed.",
        claimClass: C,
        sourceRefs: ref([2]),
      },
      {
        id: "rel-components-complete-set",
        from: "concept-five-components",
        type: "part-of",
        to: "concept-data-communications",
        explanation: "The five components make up the communication system.",
        claimClass: C,
        sourceRefs: ref([2, 3]),
      },
      {
        id: "rel-jitter-from-timeliness",
        from: "concept-jitter",
        type: "special-case-of",
        to: "concept-timeliness",
        explanation: "Jitter is variation that breaks even when average delay looks acceptable.",
        claimClass: N,
        sourceRefs: ref([2]),
      },
      {
        id: "rel-protocol-not-media",
        from: "concept-protocol-basic",
        type: "differs-from",
        to: "concept-transmission-medium",
        explanation: "Medium is physical path; protocol is governing rules. Both are required components.",
        claimClass: C,
        sourceRefs: ref([2, 3]),
      },
    ],
    definitions: [
      {
        id: "def-data-communications",
        term: "Data communications",
        definition: "Exchange of data between two devices via some form of transmission medium such as a wire cable.",
        scope: "Two devices + medium + communication system",
        qualifier: "Effectiveness depends on delivery, accuracy, timeliness, jitter",
        authoritative: true,
        claimClass: C,
        sourceRefs: ref([2]),
      },
      {
        id: "def-jitter",
        term: "Jitter",
        definition: "Variation in the packet arrival time (uneven delay in audio/video packets).",
        authoritative: true,
        claimClass: C,
        sourceRefs: ref([2]),
      },
      {
        id: "def-protocol-basic",
        term: "Protocol (basic)",
        definition: "A set of rules that govern data communications; an agreement between communicating devices.",
        qualifier: "Connection without protocol does not imply communication",
        authoritative: true,
        claimClass: C,
        sourceRefs: ref([3]),
      },
    ],
    formulas: [],
    examples: [
      {
        id: "ex-jitter-video",
        title: "Jitter with 30 ms packet interval",
        conceptIds: ["concept-jitter"],
        scenario: "Video packets are produced every 30 ms.",
        inputs: ["production interval 30 ms", "some packets arrive with 30 ms delay", "other packets with 40 ms delay"],
        reasoning: [
          "Arrival times vary around the production interval.",
          "Variable delay produces uneven quality even if mean delay is acceptable.",
        ],
        result: "Uneven video quality",
        lesson: "Timeliness for media includes stability of delay, not only average latency.",
        claimClass: C,
        sourceRefs: ref([2], "let us assume that video packets are sent every 30 ms"),
      },
      {
        id: "ex-protocol-language",
        title: "French/Japanese protocol analogy",
        conceptIds: ["concept-protocol-basic"],
        scenario: "Two devices (or people) physically connected but without shared rules.",
        inputs: ["French-only speaker", "Japanese-only speaker"],
        reasoning: ["Physical connectivity is insufficient without a shared protocol."],
        result: "Connected but not communicating",
        lesson: "Protocol is a necessary component, not an optional software add-on.",
        claimClass: C,
        sourceRefs: ref([3]),
      },
    ],
    comparisons: [
      {
        id: "cmp-effectiveness-four",
        title: "Delivery vs Accuracy vs Timeliness vs Jitter",
        items: ["delivery", "accuracy", "timeliness", "jitter"],
        axes: [
          { axis: "what fails", values: { delivery: "wrong destination", accuracy: "altered bits", timeliness: "too late", jitter: "uneven arrival" } },
          { axis: "media sensitivity", values: { delivery: "all", accuracy: "all", timeliness: "audio/video", jitter: "audio/video" } },
        ],
        similarities: ["All four are required for effectiveness."],
        commonTrap: "Treating jitter as synonym of delay.",
        claimClass: C,
        sourceRefs: ref([2]),
      },
    ],
    applications: [],
    confusions: [
      {
        id: "conf-jitter-vs-delay",
        left: "jitter",
        right: "delay/latency",
        whyConfused: "Both relate to timing of packet arrival.",
        correctDistinction: "Delay is how long; jitter is how much that long varies.",
        examTrap: "Selecting 'high delay' when the question describes uneven arrival times.",
        sourceRelevance: "explicit",
        claimClass: C,
        sourceRefs: ref([2]),
      },
    ],
    exerciseSignals: [
      {
        id: "exsig-q1-five-components",
        sourceQuestionNumber: 1,
        conceptIds: ["concept-five-components"],
        skill: "identify",
        difficultySignal: "basic",
        claimClass: "DIRECT_SOURCE",
        sourceRefs: ref([22], "Identify the five components of a data communications system."),
      },
    ],
    prerequisites: ["topic-chapter-frame"],
    dependents: ["topic-data-representation", "topic-data-flow", "topic-protocols"],
    preservationRequirements: [
      "All five components as a complete set (never drop protocol).",
      "Four effectiveness characteristics including jitter with the 30/40 ms example.",
      "Connected ≠ communicating analogy.",
    ],
    simplificationControl: {
      acceptable: [
        "Effectiveness = delivery + accuracy + timeliness + jitter.",
        "Five components are message, sender, receiver, medium, protocol.",
      ],
      notAcceptable: [
        "Dropping jitter because it is 'advanced'.",
        "Equating protocol with transmission medium.",
      ],
    },
    evidenceQuality: "high",
    coverage: {
      definition: true,
      mechanism: true,
      relationships: true,
      examples: true,
      comparisons: true,
      formulas: false,
      confusions: true,
    },
    uncertainties: [],
  },
];
