import { ref, C, N } from "./helpers.mjs";

export const topicsB = [
  {
    topicId: "topic-data-representation",
    title: "Data representation: text, numbers, images, audio, video",
    importance: "core",
    sourceSection: "1.1 Data Representation",
    sourceRefs: ref([3, 4], "Information today comes in different forms such as text, numbers, images, audio, and video."),
    learningObjectives: [
      "Explain bit-pattern representation of text and numbers",
      "Relate Unicode and ASCII as stated in the source",
      "Describe images as pixel matrices with bit-depth color",
      "Distinguish continuous vs discrete audio/video",
    ],
    concepts: [
      {
        id: "concept-bit-pattern",
        title: "Bit pattern representation",
        meaning: "Text and numbers are represented as sequences of bits (0s or 1s).",
        explanation: {
          what: "Digital systems encode information as bit sequences.",
          why: "Computers process bits; agreed codes make symbols meaningful.",
          how: "Codes map symbols to bit patterns; coding is the representation process.",
        },
        importance: "high",
        whyExamRelevant: "Foundation for Unicode/ASCII and pixel questions (ex. 14–15).",
        claimClass: C,
        sourceRefs: ref([3]),
        prerequisites: ["concept-data"],
        relatedConceptIds: ["concept-unicode-ascii", "concept-coding", "concept-pixels"],
        commonConfusionIds: [],
      },
      {
        id: "concept-coding",
        title: "Code and coding",
        meaning: "A code is a set of bit patterns for text symbols; coding is representing symbols with those patterns.",
        explanation: {
          what: "Terminology for symbol→bit mapping systems.",
          concrete: "Unicode and ASCII are codes.",
        },
        importance: "medium",
        whyExamRelevant: "Vocabulary used when defining Unicode/ASCII.",
        claimClass: C,
        sourceRefs: ref([3]),
        prerequisites: ["concept-bit-pattern"],
        relatedConceptIds: ["concept-unicode-ascii"],
        commonConfusionIds: [],
      },
      {
        id: "concept-unicode-ascii",
        title: "Unicode and ASCII (as stated in source)",
        meaning: "Unicode uses 32 bits (this source) to represent a symbol/character used in any language; ASCII is the first 127 characters / Basic Latin.",
        explanation: {
          what: "Text coding systems.",
          why: "World-language coverage vs older US-centric code.",
          how: "ASCII constitutes the first 127 Unicode characters (Basic Latin).",
          notMeaning: "This extract states 32-bit Unicode — do not silently 'correct' to UTF-8/UTF-16 without marking EXTERNAL_CONTEXT.",
        },
        importance: "high",
        whyExamRelevant: "Exercise 14 asks maximum Unicode character/symbol capacity in this framing.",
        claimClass: C,
        sourceRefs: ref([3], "Unicode, which uses 32 bits to represent a symbol or character"),
        prerequisites: ["concept-coding"],
        relatedConceptIds: ["concept-bit-pattern"],
        commonConfusionIds: [],
      },
      {
        id: "concept-numbers-binary",
        title: "Numbers as binary values",
        meaning: "Numbers are bit patterns but not via ASCII; the number is converted directly to binary to simplify math.",
        explanation: {
          what: "Numeric encoding differs from textual digit encoding.",
          why: "Direct binary conversion simplifies mathematical operations.",
          notMeaning: "ASCII is not used to represent numbers in this source's account.",
        },
        importance: "medium",
        whyExamRelevant: "Clarifies why '123' as text ≠ 123 as number.",
        claimClass: C,
        sourceRefs: ref([3]),
        prerequisites: ["concept-bit-pattern"],
        relatedConceptIds: ["concept-bit-pattern"],
        commonConfusionIds: [],
      },
      {
        id: "concept-pixels",
        title: "Images as pixel matrices",
        meaning: "An image is a matrix of pixels; each pixel has a bit pattern whose size/value depend on color depth and content.",
        explanation: {
          what: "Resolution vs memory tradeoff; black-white needs 1 bit; gray levels need more bits; RGB mixes red/green/blue.",
          how: "1000 vs 10000 pixels → better resolution, more memory.",
          whenChanges: "More gray levels or colors ⇒ more bits per pixel ⇒ more memory.",
          concrete: "4 gray levels = 2-bit patterns: 00 black, 01 dark gray, 10 light gray, 11 white.",
        },
        importance: "high",
        whyExamRelevant: "Exercise 15: 16 bits/pixel max colors.",
        claimClass: C,
        sourceRefs: ref([3, 4]),
        prerequisites: ["concept-bit-pattern"],
        relatedConceptIds: ["concept-bit-pattern"],
        commonConfusionIds: [],
      },
      {
        id: "concept-audio-video-continuous",
        title: "Audio/video continuous vs discrete",
        meaning: "Audio from a microphone is continuous; video can be continuous (camera) or a sequence of images. Both can later become digital or analog signals.",
        explanation: {
          what: "Source nature vs signal encoding.",
          how: "Chapters 4–5 (forward ref) cover changing sound/video to digital or analog.",
        },
        importance: "medium",
        whyExamRelevant: "Supports real-time/jitter context; not a heavy computation area in Ch.1.",
        claimClass: C,
        sourceRefs: ref([4]),
        prerequisites: ["concept-message"],
        relatedConceptIds: ["concept-realtime"],
        commonConfusionIds: [],
      },
    ],
    relationships: [
      {
        id: "rel-ascii-inside-unicode",
        from: "concept-unicode-ascii",
        type: "special-case-of",
        to: "concept-bit-pattern",
        explanation: "ASCII is the first 127 Unicode characters (Basic Latin) in this source.",
        claimClass: C,
        sourceRefs: ref([3]),
      },
      {
        id: "rel-pixels-bit-depth",
        from: "concept-pixels",
        type: "depends-on",
        to: "concept-bit-pattern",
        explanation: "Pixel color/gray encoding uses bit patterns; depth determines representable values.",
        claimClass: C,
        sourceRefs: ref([3, 4]),
      },
    ],
    definitions: [
      {
        id: "def-unicode",
        term: "Unicode",
        definition: "Coding system using 32 bits (per this source) to represent a symbol or character used in any language.",
        qualifier: "Source states 32-bit; preserve as source claim",
        authoritative: true,
        claimClass: C,
        sourceRefs: ref([3]),
      },
      {
        id: "def-ascii",
        term: "ASCII",
        definition: "American Standard Code for Information Interchange; first 127 Unicode characters / Basic Latin.",
        authoritative: true,
        claimClass: C,
        sourceRefs: ref([3]),
      },
      {
        id: "def-code",
        term: "Code (text)",
        definition: "A set of bit patterns designed to represent text symbols.",
        authoritative: true,
        claimClass: C,
        sourceRefs: ref([3]),
      },
    ],
    formulas: [
      {
        id: "formula-color-count",
        name: "Color count from pixel bit depth",
        latex: "colors = 2^{bits}",
        measures: "Maximum distinct colors representable per pixel",
        whenUsed: "Fixed bits-per-pixel color encoding questions",
        variables: [
          { symbol: "bits", meaning: "bits per pixel", unit: "bits" },
          { symbol: "colors", meaning: "distinct color values", unit: "count" },
        ],
        conditions: ["Uniform bits-per-pixel encoding"],
        interpretation: "Each additional bit doubles the representable color set.",
        variableChangeEffects: [
          "bits=1 → 2 colors",
          "bits=2 → 4 colors (gray example)",
          "bits=16 → 65536 colors",
        ],
        commonMistakes: [
          "Confusing bits per pixel with total image memory",
          "Using addition instead of exponentiation",
        ],
        sourceExampleId: "ex-16bit-color",
        claimClass: C,
        sourceRefs: ref([22], "A color image uses 16 bits to represent a pixel. What is the maximum number of different colors"),
      },
    ],
    examples: [
      {
        id: "ex-gray-2bit",
        title: "Two-bit grayscale encoding",
        conceptIds: ["concept-pixels"],
        scenario: "Image uses gray scale with four levels.",
        inputs: ["4 gray levels"],
        reasoning: ["Assign 00, 01, 10, 11 to black, dark gray, light gray, white."],
        result: "2-bit pattern per pixel",
        lesson: "Bit depth is determined by number of distinguishable values.",
        claimClass: C,
        sourceRefs: ref([3]),
      },
      {
        id: "ex-16bit-color",
        title: "16-bit color image max colors",
        conceptIds: ["concept-pixels"],
        scenario: "Exercise 15: color image uses 16 bits per pixel.",
        inputs: ["16 bits/pixel"],
        reasoning: ["colors = 2^16"],
        result: "65536 colors",
        lesson: "Apply exponential growth of bit patterns, not linear count of bits.",
        claimClass: C,
        sourceRefs: ref([22]),
      },
    ],
    comparisons: [
      {
        id: "cmp-info-forms",
        title: "Forms of information",
        items: ["text", "numbers", "images", "audio", "video"],
        axes: [
          {
            axis: "representation",
            values: {
              text: "bit patterns via codes (Unicode/ASCII)",
              numbers: "direct binary conversion",
              images: "pixel matrix + bit depth",
              audio: "continuous then digital/analog",
              video: "continuous or image sequence",
            },
          },
        ],
        similarities: ["All ultimately need digital encoding for data communication."],
        claimClass: C,
        sourceRefs: ref([3, 4]),
      },
    ],
    applications: [],
    confusions: [
      {
        id: "conf-ascii-vs-number",
        left: "ASCII digit characters",
        right: "binary numeric value",
        whyConfused: "Both involve 0/1 and digits.",
        correctDistinction: "Source says numbers are converted directly to binary, not represented with ASCII.",
        examTrap: "Assuming ASCII encodes numeric values for arithmetic.",
        sourceRelevance: "explicit",
        claimClass: C,
        sourceRefs: ref([3]),
      },
    ],
    exerciseSignals: [
      {
        id: "exsig-q14-unicode",
        sourceQuestionNumber: 14,
        conceptIds: ["concept-unicode-ascii"],
        skill: "compute",
        distinctionTested: "Unicode capacity framing",
        difficultySignal: "basic",
        claimClass: "DIRECT_SOURCE",
        sourceRefs: ref([22], "What is the maximum number of characters or symbols that can be represented by Unicode?"),
      },
      {
        id: "exsig-q15-colors",
        sourceQuestionNumber: 15,
        conceptIds: ["concept-pixels"],
        skill: "compute",
        formulaTested: "formula-color-count",
        difficultySignal: "basic",
        claimClass: "DIRECT_SOURCE",
        sourceRefs: ref([22]),
      },
    ],
    prerequisites: ["topic-data-communication"],
    dependents: ["topic-data-flow", "topic-networks-criteria"],
    preservationRequirements: [
      "All five information forms with distinct representation rules.",
      "Unicode 32-bit claim as stated + ASCII as Basic Latin.",
      "Pixel bit-depth → color count formula with 16-bit exercise.",
    ],
    simplificationControl: {
      acceptable: ["Images are pixel matrices; more bits/pixel ⇒ more colors and more memory."],
      notAcceptable: ["Silently replacing source '32-bit Unicode' with UTF-8 without marking EXTERNAL_CONTEXT."],
    },
    evidenceQuality: "high",
    coverage: {
      definition: true,
      mechanism: true,
      relationships: true,
      examples: true,
      comparisons: true,
      formulas: true,
      confusions: true,
    },
    uncertainties: [
      "Unicode bit-width is a source claim; modern Unicode encodings differ — flag for CGP-2 if chapter needs accuracy notes.",
    ],
  },
  {
    topicId: "topic-data-flow",
    title: "Data flow: simplex, half-duplex, full-duplex",
    importance: "core",
    sourceSection: "1.1 Data Flow",
    sourceRefs: ref([4, 5], "Communication between two devices can be simplex, half-duplex, or full-duplex."),
    learningObjectives: [
      "Classify a link as simplex, half-duplex, or full-duplex",
      "Explain capacity use in each mode",
      "Give device examples for each mode",
    ],
    concepts: [
      {
        id: "concept-simplex",
        title: "Simplex",
        meaning: "Unidirectional communication; only one of two devices can transmit; the other can only receive.",
        explanation: {
          what: "One-way street.",
          how: "Entire channel capacity can be used to send data in one direction.",
          concrete: "Keyboards and traditional monitors.",
          notMeaning: "Not half of half-duplex; there is no reverse data path for the other device to send.",
        },
        importance: "high",
        whyExamRelevant: "One of three flow modes; direction/capacity details are exam favorites.",
        claimClass: C,
        sourceRefs: ref([4]),
        prerequisites: ["concept-transmission-medium"],
        relatedConceptIds: ["concept-half-duplex", "concept-full-duplex"],
        commonConfusionIds: ["conf-half-vs-full"],
      },
      {
        id: "concept-half-duplex",
        title: "Half-duplex",
        meaning: "Each station can both transmit and receive, but not at the same time.",
        explanation: {
          what: "Two-way, one direction at a time.",
          how: "Entire capacity is taken over by whichever device transmits at the time.",
          concrete: "Walkie-talkies and CB radios.",
          whenChanges: "When both directions are never needed simultaneously, full capacity can be used per direction.",
        },
        importance: "high",
        whyExamRelevant: "Review Q7 contrasts it with full-duplex.",
        claimClass: C,
        sourceRefs: ref([4, 5]),
        prerequisites: ["concept-simplex"],
        relatedConceptIds: ["concept-full-duplex"],
        commonConfusionIds: ["conf-half-vs-full"],
      },
      {
        id: "concept-full-duplex",
        title: "Full-duplex (duplex)",
        meaning: "Both stations can transmit and receive simultaneously.",
        explanation: {
          what: "Two-way street with simultaneous traffic.",
          how: "Either two physically separate transmission paths, or capacity divided between directions.",
          concrete: "Telephone network — both talk and listen at once.",
          whenChanges: "Capacity must be divided between directions when a single medium is shared.",
        },
        importance: "high",
        whyExamRelevant: "Third mode; capacity-sharing mechanism is a common deep question.",
        claimClass: C,
        sourceRefs: ref([5]),
        prerequisites: ["concept-half-duplex"],
        relatedConceptIds: ["concept-half-duplex"],
        commonConfusionIds: ["conf-half-vs-full"],
      },
    ],
    relationships: [
      {
        id: "rel-half-vs-full-capacity",
        from: "concept-half-duplex",
        type: "contrasts",
        to: "concept-full-duplex",
        explanation: "Half-duplex can dedicate entire capacity to one direction at a time; full-duplex must share capacity continuously.",
        claimClass: C,
        sourceRefs: ref([4, 5]),
      },
      {
        id: "rel-simplex-unidirectional",
        from: "concept-simplex",
        type: "differs-from",
        to: "concept-half-duplex",
        explanation: "Simplex never allows the receiving device to transmit on that link.",
        claimClass: C,
        sourceRefs: ref([4]),
      },
    ],
    definitions: [
      {
        id: "def-simplex",
        term: "Simplex mode",
        definition: "Unidirectional communication on a link between two devices.",
        authoritative: true,
        claimClass: C,
        sourceRefs: ref([4]),
      },
      {
        id: "def-half-duplex",
        term: "Half-duplex mode",
        definition: "Each station can transmit and receive, but not at the same time.",
        authoritative: true,
        claimClass: C,
        sourceRefs: ref([4, 5]),
      },
      {
        id: "def-full-duplex",
        term: "Full-duplex mode",
        definition: "Both stations can transmit and receive simultaneously (also called duplex).",
        qualifier: "Capacity shared via two paths or divided link capacity",
        authoritative: true,
        claimClass: C,
        sourceRefs: ref([5]),
      },
    ],
    formulas: [],
    examples: [
      {
        id: "ex-flow-devices",
        title: "Device examples per mode",
        conceptIds: ["concept-simplex", "concept-half-duplex", "concept-full-duplex"],
        scenario: "Map everyday devices to directionality models.",
        inputs: ["keyboard", "monitor", "walkie-talkie", "telephone"],
        reasoning: [
          "Keyboard only inputs; monitor only outputs → simplex.",
          "Walkie-talkie: one talks, other listens, then swap → half-duplex.",
          "Telephone: simultaneous talk/listen → full-duplex.",
        ],
        result: "simplex / half-duplex / full-duplex",
        lesson: "Classify by whether send and receive can occur simultaneously.",
        claimClass: C,
        sourceRefs: ref([4, 5]),
      },
    ],
    comparisons: [
      {
        id: "cmp-data-flow",
        title: "Simplex vs Half-duplex vs Full-duplex",
        items: ["simplex", "half-duplex", "full-duplex"],
        axes: [
          {
            axis: "direction",
            values: { simplex: "one-way", "half-duplex": "two-way alternate", "full-duplex": "two-way simultaneous" },
          },
          {
            axis: "capacity use",
            values: {
              simplex: "entire capacity one direction",
              "half-duplex": "entire capacity to current transmitter",
              "full-duplex": "shared/divided capacity",
            },
          },
          {
            axis: "examples",
            values: {
              simplex: "keyboard, traditional monitor",
              "half-duplex": "walkie-talkie, CB radio",
              "full-duplex": "telephone network",
            },
          },
        ],
        similarities: ["All involve two devices on a link."],
        commonTrap: "Calling half-duplex 'full two-way' without the simultaneity qualifier.",
        claimClass: C,
        sourceRefs: ref([4, 5]),
      },
    ],
    applications: [],
    confusions: [
      {
        id: "conf-half-vs-full",
        left: "half-duplex",
        right: "full-duplex",
        whyConfused: "Both allow two-way communication.",
        correctDistinction: "Only full-duplex allows simultaneous transmit and receive.",
        examTrap: "Choosing half-duplex when the scenario requires simultaneous talk/listen.",
        sourceRelevance: "explicit",
        claimClass: C,
        sourceRefs: ref([4, 5, 22], "Review Q7: difference between half-duplex and full-duplex."),
      },
    ],
    exerciseSignals: [
      {
        id: "exsig-q7-half-full",
        sourceQuestionNumber: 7,
        conceptIds: ["concept-half-duplex", "concept-full-duplex"],
        skill: "compare",
        distinctionTested: "half-duplex vs full-duplex",
        difficultySignal: "basic",
        claimClass: "DIRECT_SOURCE",
        sourceRefs: ref([22]),
      },
    ],
    prerequisites: ["topic-data-communication"],
    dependents: ["topic-networks-criteria", "topic-physical-structures"],
    preservationRequirements: [
      "Three modes with direction + capacity semantics + one device example each.",
      "Half vs full simultaneity distinction.",
    ],
    simplificationControl: {
      acceptable: ["Half-duplex = two-way, not at the same time."],
      notAcceptable: ["Saying full-duplex is just 'faster half-duplex'."],
    },
    evidenceQuality: "high",
    coverage: {
      definition: true,
      mechanism: true,
      relationships: true,
      examples: true,
      comparisons: true,
      formulas: false,
      confusions: true,
    },
    uncertainties: [],
  },
  {
    topicId: "topic-networks-criteria",
    title: "Networks: definition, distributed processing, criteria",
    importance: "core",
    sourceSection: "1.2 NETWORKS",
    sourceRefs: ref([5, 6], "A network is a set of devices (often referred to as nodes) connected by communication links."),
    learningObjectives: [
      "Define network and node",
      "Explain distributed processing",
      "State the three network criteria",
      "Explain the throughput–delay tradeoff",
    ],
    concepts: [
      {
        id: "concept-network",
        title: "Network",
        meaning: "A set of devices (nodes) connected by communication links.",
        explanation: {
          what: "Devices + links.",
          notMeaning: "Not automatically the Internet; not automatically an internetwork.",
        },
        importance: "high",
        whyExamRelevant: "Core definition; review Q11 contrasts network vs Internet.",
        claimClass: C,
        sourceRefs: ref([5], "A network is a set of devices (often referred to as nodes) connected by communication links."),
        prerequisites: ["concept-data-communications"],
        relatedConceptIds: ["concept-node", "concept-link", "concept-internetwork"],
        commonConfusionIds: ["conf-network-vs-internet"],
      },
      {
        id: "concept-node",
        title: "Node",
        meaning: "Computer, printer, or any other device capable of sending and/or receiving data generated by other nodes.",
        explanation: {
          what: "Any communicating device on the network.",
        },
        importance: "high",
        whyExamRelevant: "Terminology used in topology counts (n nodes).",
        claimClass: C,
        sourceRefs: ref([5]),
        prerequisites: ["concept-network"],
        relatedConceptIds: ["concept-network"],
        commonConfusionIds: [],
      },
      {
        id: "concept-distributed-processing",
        title: "Distributed processing",
        meaning: "A task is divided among multiple computers; each handles a subset instead of one large machine owning all aspects.",
        explanation: {
          what: "Workload split across machines.",
          why: "Avoids single-machine responsibility for an entire process.",
        },
        importance: "medium",
        whyExamRelevant: "Review Q2 asks advantages of distributed processing.",
        claimClass: C,
        sourceRefs: ref([5], "Most networks use distributed processing"),
        prerequisites: ["concept-network"],
        relatedConceptIds: ["concept-network"],
        commonConfusionIds: [],
      },
      {
        id: "concept-network-criteria",
        title: "Network criteria",
        meaning: "The most important criteria a network must meet are performance, reliability, and security.",
        explanation: {
          what: "Evaluation triad.",
          parts: ["performance", "reliability", "security"],
        },
        importance: "high",
        whyExamRelevant: "Review Q3; missing from the current sample chapter.",
        claimClass: C,
        sourceRefs: ref([5, 6], "The most important of these are performance, reliability, and security."),
        prerequisites: ["concept-network"],
        relatedConceptIds: ["concept-performance-metrics", "concept-reliability", "concept-security"],
        commonConfusionIds: ["conf-bandwidth-throughput"],
      },
      {
        id: "concept-performance-metrics",
        title: "Performance metrics",
        meaning: "Transit time and response time; often evaluated as throughput and delay.",
        explanation: {
          what: "Transit time = message travel time device-to-device; response time = elapsed time between inquiry and response.",
          why: "Performance depends on number of users, medium type, hardware capabilities, software efficiency.",
          whenChanges: "Sending more data may increase throughput but also delay via congestion.",
          notMeaning: "Performance is not only raw speed/bandwidth.",
        },
        importance: "high",
        whyExamRelevant: "Throughput–delay contradiction is a classic conceptual item.",
        claimClass: C,
        sourceRefs: ref([5, 6], "If we try to send more data to the network, we may increase throughput but we increase the delay"),
        prerequisites: ["concept-network-criteria"],
        relatedConceptIds: ["concept-throughput", "concept-delay"],
        commonConfusionIds: ["conf-bandwidth-throughput"],
      },
      {
        id: "concept-throughput",
        title: "Throughput",
        meaning: "Networking metric of data successfully handled (desired higher).",
        explanation: {
          what: "One of two evaluation metrics named with delay.",
          whenChanges: "Can rise with offered load, at cost of delay.",
        },
        importance: "high",
        whyExamRelevant: "Paired with delay in tradeoff questions.",
        claimClass: C,
        sourceRefs: ref([6], "Performance is often evaluated by two networking metrics: throughput and delay."),
        prerequisites: ["concept-performance-metrics"],
        relatedConceptIds: ["concept-delay"],
        commonConfusionIds: ["conf-bandwidth-throughput"],
      },
      {
        id: "concept-delay",
        title: "Delay",
        meaning: "Networking performance metric of time cost (desired lower); increases under congestion.",
        explanation: {
          what: "Time penalty metric.",
          whenChanges: "Traffic congestion increases delay.",
        },
        importance: "high",
        whyExamRelevant: "Tradeoff partner of throughput; exercise 23 is delay-sensitivity.",
        claimClass: C,
        sourceRefs: ref([6]),
        prerequisites: ["concept-performance-metrics"],
        relatedConceptIds: ["concept-throughput"],
        commonConfusionIds: [],
      },
      {
        id: "concept-reliability",
        title: "Reliability",
        meaning: "Measured by frequency of failure, time to recover from a link failure, and robustness in a catastrophe.",
        explanation: {
          what: "Beyond accuracy of delivery — failure frequency, recovery time, catastrophe robustness.",
        },
        importance: "medium",
        whyExamRelevant: "One of three criteria; often under-taught.",
        claimClass: C,
        sourceRefs: ref([6]),
        prerequisites: ["concept-network-criteria"],
        relatedConceptIds: ["concept-network-criteria"],
        commonConfusionIds: [],
      },
      {
        id: "concept-security",
        title: "Security",
        meaning: "Protect data from unauthorized access and damage; implement policies/procedures for recovery from breaches and losses.",
        explanation: {
          what: "Confidentiality/integrity/recovery policy layer.",
        },
        importance: "medium",
        whyExamRelevant: "One of three criteria.",
        claimClass: C,
        sourceRefs: ref([6]),
        prerequisites: ["concept-network-criteria"],
        relatedConceptIds: ["concept-network-criteria"],
        commonConfusionIds: [],
      },
    ],
    relationships: [
      {
        id: "rel-throughput-delay-tradeoff",
        from: "concept-throughput",
        type: "contrasts",
        to: "concept-delay",
        explanation: "Often contradictory: more offered data can raise throughput and raise delay via congestion.",
        claimClass: C,
        sourceRefs: ref([6]),
      },
      {
        id: "rel-performance-factors",
        from: "concept-performance-metrics",
        type: "depends-on",
        to: "concept-network",
        explanation: "Depends on users, medium, hardware capabilities, software efficiency.",
        claimClass: C,
        sourceRefs: ref([5, 6]),
      },
    ],
    definitions: [
      {
        id: "def-network",
        term: "Network",
        definition: "A set of devices (nodes) connected by communication links.",
        authoritative: true,
        claimClass: C,
        sourceRefs: ref([5]),
      },
      {
        id: "def-distributed-processing",
        term: "Distributed processing",
        definition: "Division of a task among multiple computers so each handles a subset.",
        authoritative: true,
        claimClass: C,
        sourceRefs: ref([5]),
      },
      {
        id: "def-throughput",
        term: "Throughput",
        definition: "Networking performance metric of data successfully transferred (often desired higher).",
        qualifier: "Not defined as link bandwidth in this chapter",
        authoritative: true,
        claimClass: C,
        sourceRefs: ref([6]),
      },
      {
        id: "def-delay",
        term: "Delay",
        definition: "Networking performance metric of time cost (often desired lower).",
        authoritative: true,
        claimClass: C,
        sourceRefs: ref([6]),
      },
    ],
    formulas: [],
    examples: [],
    comparisons: [
      {
        id: "cmp-network-criteria",
        title: "Performance vs Reliability vs Security",
        items: ["performance", "reliability", "security"],
        axes: [
          {
            axis: "focus",
            values: {
              performance: "transit/response time, throughput, delay",
              reliability: "failure frequency, recovery, robustness",
              security: "unauthorized access, damage, recovery policies",
            },
          },
        ],
        similarities: ["All three are required criteria in the source."],
        claimClass: C,
        sourceRefs: ref([5, 6]),
      },
    ],
    applications: [],
    confusions: [
      {
        id: "conf-bandwidth-throughput",
        left: "bandwidth (not defined in this Ch.1 extract)",
        right: "throughput",
        whyConfused: "Sample chapter centers bandwidth; source centers throughput/delay.",
        correctDistinction: "In this source, performance evaluation uses throughput and delay; bandwidth is not given a Ch.1 definition.",
        examTrap: "Answering performance questions with a bandwidth-only story.",
        sourceRelevance: "implied",
        claimClass: N,
        sourceRefs: ref([6]),
      },
    ],
    exerciseSignals: [
      {
        id: "exsig-q2-distributed",
        sourceQuestionNumber: 2,
        conceptIds: ["concept-distributed-processing"],
        skill: "define",
        difficultySignal: "basic",
        claimClass: "DIRECT_SOURCE",
        sourceRefs: ref([22]),
      },
      {
        id: "exsig-q3-criteria",
        sourceQuestionNumber: 3,
        conceptIds: ["concept-network-criteria"],
        skill: "identify",
        difficultySignal: "basic",
        claimClass: "DIRECT_SOURCE",
        sourceRefs: ref([22]),
      },
      {
        id: "exsig-q23-delay-apps",
        sourceQuestionNumber: 23,
        conceptIds: ["concept-delay"],
        skill: "analyze",
        difficultySignal: "intermediate",
        claimClass: "DIRECT_SOURCE",
        sourceRefs: ref([23], "Performance is inversely related to delay... more sensitive to delay?"),
      },
    ],
    prerequisites: ["topic-data-communication"],
    dependents: ["topic-physical-structures", "topic-network-categories"],
    preservationRequirements: [
      "Three criteria: performance, reliability, security.",
      "Throughput–delay contradiction under load.",
      "Distributed processing definition.",
    ],
    simplificationControl: {
      acceptable: ["More traffic can raise throughput and delay together."],
      notAcceptable: ["Higher bandwidth always makes every network faster (not source-stated here)."],
    },
    evidenceQuality: "high",
    coverage: {
      definition: true,
      mechanism: true,
      relationships: true,
      examples: false,
      comparisons: true,
      formulas: false,
      confusions: true,
    },
    uncertainties: [],
  },
];
