import { ref, C, N } from "./helpers.mjs";

export const topicsC = [
  {
    topicId: "topic-physical-structures",
    title: "Physical structures: connections and topologies",
    importance: "core",
    sourceSection: "1.2 Physical Structures",
    sourceRefs: ref([6, 7, 8, 9, 10, 11], "There are two possible types of connections: point-to-point and multipoint."),
    learningObjectives: [
      "Distinguish point-to-point and multipoint connections",
      "Classify mesh, star, bus, ring (and hybrid) topologies",
      "Apply mesh link and port formulas",
      "Explain advantages/disadvantages and failure modes of each basic topology",
    ],
    concepts: [
      {
        id: "concept-link",
        title: "Link",
        meaning: "A communications pathway that transfers data from one device to another.",
        explanation: {
          what: "Edge in the network graph.",
          how: "Imagined as a line between two points for visualization.",
        },
        importance: "medium",
        whyExamRelevant: "Needed to count cables in topology exercises.",
        claimClass: C,
        sourceRefs: ref([6]),
        prerequisites: ["concept-network"],
        relatedConceptIds: ["concept-point-to-point", "concept-topology"],
        commonConfusionIds: ["conf-links-vs-ports"],
      },
      {
        id: "concept-point-to-point",
        title: "Point-to-point connection",
        meaning: "Dedicated link between two devices; entire capacity reserved for those two.",
        explanation: {
          what: "Two-device exclusive link.",
          how: "Usually wire/cable; can be microwave or satellite.",
          concrete: "Infrared remote establishing a connection to a TV control system.",
        },
        importance: "high",
        whyExamRelevant: "Review Q4–Q5; prerequisite for mesh/star classification.",
        claimClass: C,
        sourceRefs: ref([6], "A point-to-point connection provides a dedicated link between two devices."),
        prerequisites: ["concept-link"],
        relatedConceptIds: ["concept-multipoint", "concept-mesh", "concept-star", "concept-ring"],
        commonConfusionIds: [],
      },
      {
        id: "concept-multipoint",
        title: "Multipoint (multidrop) connection",
        meaning: "More than two specific devices share a single link.",
        explanation: {
          what: "Shared link among 3+ devices.",
          how: "Capacity shared spatially (simultaneous) or temporally (turns).",
        },
        importance: "high",
        whyExamRelevant: "Prerequisite for bus topology; review Q4.",
        claimClass: C,
        sourceRefs: ref([6], "A multipoint (also called multidrop) connection is one in which more than two specific devices share a single link."),
        prerequisites: ["concept-link"],
        relatedConceptIds: ["concept-point-to-point", "concept-bus"],
        commonConfusionIds: [],
      },
      {
        id: "concept-topology",
        title: "Physical topology",
        meaning: "Geometric representation of the relationship of all links and linking devices (nodes) to one another.",
        explanation: {
          what: "Arrangement pattern of the network.",
          parts: ["mesh", "star", "bus", "ring", "hybrid"],
        },
        importance: "high",
        whyExamRelevant: "Largest knowledge block; review Q6/Q8/Q9.",
        claimClass: C,
        sourceRefs: ref([7]),
        prerequisites: ["concept-point-to-point", "concept-multipoint"],
        relatedConceptIds: ["concept-mesh", "concept-star", "concept-bus", "concept-ring", "concept-hybrid"],
        commonConfusionIds: [],
      },
      {
        id: "concept-mesh",
        title: "Mesh topology",
        meaning: "Every device has a dedicated point-to-point link to every other device.",
        explanation: {
          what: "Fully connected dedicated links.",
          how: "n(n−1)/2 duplex links; n−1 I/O ports per device.",
          parts: ["dedicated links", "n-1 ports", "robustness", "privacy", "fault isolation"],
          whenChanges: "Adding a node increases links ~quadratically.",
          concrete: "Telephone regional offices needing mutual connectivity (limited mesh backbone).",
          notMeaning: "Not the same as 'many links' without full connectivity.",
        },
        importance: "high",
        whyExamRelevant: "Only source body formulas live here; exercises 9/16/17.",
        claimClass: C,
        sourceRefs: ref([7, 8, 9], "In a mesh topology, every device has a dedicated point-to-point link to every other device."),
        prerequisites: ["concept-point-to-point", "concept-topology"],
        relatedConceptIds: ["concept-star", "concept-bus", "concept-ring"],
        commonConfusionIds: ["conf-links-vs-ports"],
      },
      {
        id: "concept-star",
        title: "Star topology",
        meaning: "Each device has a dedicated point-to-point link only to a central controller (hub); devices are not directly linked.",
        explanation: {
          what: "Hub-centered exchange.",
          how: "Controller relays data between devices.",
          whenChanges: "If hub dies, whole system dies (single point of failure).",
          concrete: "High-speed LANs with central hub.",
        },
        importance: "high",
        whyExamRelevant: "Common LAN topology; failure-mode questions.",
        claimClass: C,
        sourceRefs: ref([8, 9]),
        prerequisites: ["concept-point-to-point", "concept-topology"],
        relatedConceptIds: ["concept-hub", "concept-mesh"],
        commonConfusionIds: [],
      },
      {
        id: "concept-hub",
        title: "Hub (central controller)",
        meaning: "Central device in a star topology that acts as an exchange between stations.",
        explanation: {
          what: "Single point of dependency for star.",
          how: "Can monitor link problems and bypass defective links while working.",
        },
        importance: "high",
        whyExamRelevant: "Explains star advantages/disadvantages.",
        claimClass: C,
        sourceRefs: ref([8, 9]),
        prerequisites: ["concept-star"],
        relatedConceptIds: ["concept-star"],
        commonConfusionIds: [],
      },
      {
        id: "concept-bus",
        title: "Bus topology",
        meaning: "Multipoint topology with one long cable as backbone; nodes connect via drop lines and taps.",
        explanation: {
          what: "Shared backbone.",
          how: "Signal weakens along the backbone (energy → heat); tap count/distance limited.",
          whenChanges: "Break in bus cable stops all transmission; reflections create noise.",
          concrete: "Early Ethernet LANs (less popular now per source).",
        },
        importance: "high",
        whyExamRelevant: "Line-configuration classification + failure analysis (ex. 17c, 20).",
        claimClass: C,
        sourceRefs: ref([9, 10]),
        prerequisites: ["concept-multipoint", "concept-topology"],
        relatedConceptIds: ["concept-drop-line", "concept-tap"],
        commonConfusionIds: [],
      },
      {
        id: "concept-drop-line",
        title: "Drop line",
        meaning: "Connection running between the device and the main bus cable.",
        explanation: { what: "Device attachment path to backbone." },
        importance: "medium",
        whyExamRelevant: "Bus anatomy vocabulary.",
        claimClass: C,
        sourceRefs: ref([9]),
        prerequisites: ["concept-bus"],
        relatedConceptIds: ["concept-tap", "concept-bus"],
        commonConfusionIds: [],
      },
      {
        id: "concept-tap",
        title: "Tap",
        meaning: "Connector that splices into or punctures the cable sheathing to contact the metallic core.",
        explanation: { what: "Physical connector onto the bus backbone." },
        importance: "medium",
        whyExamRelevant: "Bus anatomy vocabulary.",
        claimClass: C,
        sourceRefs: ref([9]),
        prerequisites: ["concept-bus"],
        relatedConceptIds: ["concept-drop-line"],
        commonConfusionIds: [],
      },
      {
        id: "concept-ring",
        title: "Ring topology",
        meaning: "Each device has dedicated point-to-point connections only to the two neighbors; signal passed along the ring; each device incorporates a repeater.",
        explanation: {
          what: "Closed loop with regeneration at each device.",
          how: "Unidirectional traffic; dual ring or switch can mitigate breaks.",
          whenChanges: "Simple ring break can disable entire network.",
          concrete: "IBM Token Ring (historical prevalence).",
        },
        importance: "high",
        whyExamRelevant: "Failure modes and line configuration (ex. 6, 17d, 19).",
        claimClass: C,
        sourceRefs: ref([10, 11]),
        prerequisites: ["concept-point-to-point", "concept-topology"],
        relatedConceptIds: ["concept-star", "concept-bus"],
        commonConfusionIds: [],
      },
      {
        id: "concept-hybrid",
        title: "Hybrid topology",
        meaning: "Combination of topologies, e.g., main star with each branch connecting several stations in bus topology.",
        explanation: {
          what: "Composite physical design.",
          concrete: "Star backbone with three bus networks.",
        },
        importance: "medium",
        whyExamRelevant: "Exercises 21–22 ask students to draw hybrids.",
        claimClass: C,
        sourceRefs: ref([11]),
        prerequisites: ["concept-star", "concept-bus", "concept-ring"],
        relatedConceptIds: ["concept-topology"],
        commonConfusionIds: [],
      },
    ],
    relationships: [
      {
        id: "rel-mesh-from-p2p",
        from: "concept-mesh",
        type: "depends-on",
        to: "concept-point-to-point",
        explanation: "Mesh is built from dedicated p2p links between every pair.",
        claimClass: C,
        sourceRefs: ref([7]),
      },
      {
        id: "rel-bus-is-multipoint",
        from: "concept-bus",
        type: "special-case-of",
        to: "concept-multipoint",
        explanation: "Bus is the multipoint topology; star/mesh/ring use p2p links.",
        claimClass: C,
        sourceRefs: ref([9]),
      },
      {
        id: "rel-star-hub-spof",
        from: "concept-hub",
        type: "affects",
        to: "concept-star",
        explanation: "Hub failure kills the entire star system.",
        claimClass: C,
        sourceRefs: ref([9]),
      },
      {
        id: "rel-ring-repeater",
        from: "concept-ring",
        type: "depends-on",
        to: "concept-ring",
        explanation: "Each device regenerates bits via an internal repeater before passing them along.",
        claimClass: C,
        sourceRefs: ref([10]),
      },
    ],
    definitions: [
      {
        id: "def-point-to-point",
        term: "Point-to-point",
        definition: "Dedicated link between two devices; entire capacity reserved for those two.",
        authoritative: true,
        claimClass: C,
        sourceRefs: ref([6]),
      },
      {
        id: "def-multipoint",
        term: "Multipoint / multidrop",
        definition: "Connection in which more than two specific devices share a single link.",
        authoritative: true,
        claimClass: C,
        sourceRefs: ref([6]),
      },
      {
        id: "def-topology",
        term: "Physical topology",
        definition: "Geometric representation of the relationship of all links and nodes to one another.",
        authoritative: true,
        claimClass: C,
        sourceRefs: ref([7]),
      },
      {
        id: "def-drop-line",
        term: "Drop line",
        definition: "Connection running between the device and the main bus cable.",
        authoritative: true,
        claimClass: C,
        sourceRefs: ref([9]),
      },
      {
        id: "def-tap",
        term: "Tap",
        definition: "Connector that splices into or punctures cable sheathing to contact the metallic core.",
        authoritative: true,
        claimClass: C,
        sourceRefs: ref([9]),
      },
      {
        id: "def-hub",
        term: "Hub",
        definition: "Central controller in a star topology that exchanges data between devices.",
        authoritative: true,
        claimClass: C,
        sourceRefs: ref([8]),
      },
    ],
    formulas: [
      {
        id: "formula-mesh-links",
        name: "Fully connected mesh duplex links",
        latex: "\\frac{n(n-1)}{2}",
        measures: "Number of duplex-mode physical links in a fully connected mesh",
        whenUsed: "Cable/link count for mesh with n nodes",
        variables: [{ symbol: "n", meaning: "number of nodes/devices", unit: "count" }],
        conditions: ["Fully connected mesh", "Each physical link is duplex (bidirectional)"],
        interpretation: "Each of n nodes connects to n−1 others; each link counted twice, so divide by 2.",
        variableChangeEffects: [
          "n=2 → 1 link",
          "n=5 → 10 links",
          "n=6 → 15 links (exercise 16)",
        ],
        commonMistakes: [
          "Using n(n−1) without /2 for duplex links",
          "Answering ports when links were asked",
        ],
        sourceExampleId: "ex-mesh-six",
        claimClass: C,
        sourceRefs: ref([7], "we need n(n-1)/2 duplex-mode links"),
      },
      {
        id: "formula-mesh-ports",
        name: "Mesh I/O ports per device",
        latex: "ports = n - 1",
        measures: "I/O ports required on each mesh device",
        whenUsed: "Port-count questions for fully connected mesh",
        variables: [{ symbol: "n", meaning: "number of nodes/devices", unit: "count" }],
        conditions: ["Fully connected mesh"],
        interpretation: "Each device must reach the other n−1 stations.",
        variableChangeEffects: ["n=6 → 5 ports each"],
        commonMistakes: ["Giving cable count instead of port count"],
        sourceExampleId: "ex-mesh-six",
        claimClass: C,
        sourceRefs: ref([7, 8], "every device on the network must have n - 1 input/output ports"),
      },
    ],
    examples: [
      {
        id: "ex-mesh-six",
        title: "Six devices in mesh",
        conceptIds: ["concept-mesh"],
        scenario: "Exercise 16: six devices arranged in mesh topology.",
        inputs: ["n = 6"],
        reasoning: [
          "links = n(n−1)/2 = 6·5/2 = 15",
          "ports per device = n−1 = 5",
        ],
        result: "15 cables; 5 ports needed on each device",
        lesson: "Compute links and ports separately; both use n but differently.",
        claimClass: C,
        sourceRefs: ref([22], "Exercise 16: six devices mesh — cables and ports"),
      },
      {
        id: "ex-ir-tv",
        title: "IR remote point-to-point",
        conceptIds: ["concept-point-to-point"],
        scenario: "Changing TV channels by infrared remote.",
        inputs: ["remote control", "TV control system"],
        reasoning: ["Dedicated link between exactly two devices."],
        result: "point-to-point connection",
        lesson: "Point-to-point is not only long-haul cable; short dedicated links count.",
        claimClass: C,
        sourceRefs: ref([6]),
      },
      {
        id: "ex-two-lan-wan-topo",
        title: "Heterogeneous enterprise internetwork (topology angle)",
        conceptIds: ["concept-bus", "concept-star"],
        scenario: "West office bus LAN; east office star LAN; president remote via WANs.",
        inputs: ["bus LAN", "star LAN", "switched WAN", "point-to-point WANs"],
        reasoning: ["Different topologies can coexist when interconnected."],
        result: "Internetwork of heterogeneous LAN/WAN technologies",
        lesson: "Topology choice is local; internetworking is global.",
        claimClass: C,
        sourceRefs: ref([13, 14]),
      },
    ],
    comparisons: [
      {
        id: "cmp-connections",
        title: "Point-to-point vs Multipoint",
        items: ["point-to-point", "multipoint"],
        axes: [
          {
            axis: "devices on link",
            values: { "point-to-point": "exactly two", multipoint: "more than two" },
          },
          {
            axis: "capacity",
            values: {
              "point-to-point": "entire capacity reserved",
              multipoint: "shared spatially or temporally",
            },
          },
        ],
        commonTrap: "Calling a bus 'point-to-point' because each drop line is short.",
        claimClass: C,
        sourceRefs: ref([6]),
      },
      {
        id: "cmp-topologies",
        title: "Mesh vs Star vs Bus vs Ring",
        items: ["mesh", "star", "bus", "ring"],
        axes: [
          {
            axis: "line configuration",
            values: {
              mesh: "all p2p",
              star: "all p2p to hub",
              bus: "multipoint",
              ring: "p2p to two neighbors",
            },
          },
          {
            axis: "cabling",
            values: {
              mesh: "very high",
              star: "less than mesh; may exceed ring/bus",
              bus: "low (backbone + drops)",
              ring: "two connections per device",
            },
          },
          {
            axis: "failure mode",
            values: {
              mesh: "robust; one link down does not incapacitate system",
              star: "hub down kills system",
              bus: "backbone break stops all transmission",
              ring: "simple ring break can disable network",
            },
          },
          {
            axis: "fault isolation",
            values: {
              mesh: "easy (dedicated links)",
              star: "easy while hub works",
              bus: "difficult",
              ring: "simplified via circulating signal/alarms",
            },
          },
        ],
        similarities: ["All are basic physical topologies; hybrid combines them."],
        commonTrap: "Mixing mesh link count with star hub dependency.",
        claimClass: C,
        sourceRefs: ref([7, 8, 9, 10, 11]),
      },
    ],
    applications: [
      {
        id: "app-telephone-mesh",
        title: "Telephone regional offices as limited mesh",
        conceptIds: ["concept-mesh"],
        detail: "Each regional office needs connection to every other regional office — practical limited mesh backbone.",
        claimClass: C,
        sourceRefs: ref([8]),
      },
      {
        id: "app-lan-star",
        title: "High-speed LAN star",
        conceptIds: ["concept-star"],
        detail: "Source: star topology is used in LANs; high-speed LANs often use star with central hub.",
        claimClass: C,
        sourceRefs: ref([9]),
      },
      {
        id: "app-early-ethernet-bus",
        title: "Early Ethernet bus LANs",
        conceptIds: ["concept-bus"],
        detail: "Bus was among first LAN topologies; Ethernet can use bus but less popular now (Ch.13 forward ref).",
        claimClass: C,
        sourceRefs: ref([10]),
      },
    ],
    confusions: [
      {
        id: "conf-links-vs-ports",
        left: "mesh links n(n−1)/2",
        right: "mesh ports n−1 per device",
        whyConfused: "Both depend on n and appear in the same exercises.",
        correctDistinction: "Links are cables between pairs; ports are I/O interfaces on each device.",
        examTrap: "Answering 15 ports when 15 cables were asked (or vice versa) for n=6.",
        sourceRelevance: "explicit",
        claimClass: C,
        sourceRefs: ref([7, 23]),
      },
    ],
    exerciseSignals: [
      {
        id: "exsig-q4-multipoint-adv",
        sourceQuestionNumber: 4,
        conceptIds: ["concept-multipoint", "concept-point-to-point"],
        skill: "compare",
        difficultySignal: "intermediate",
        claimClass: "DIRECT_SOURCE",
        sourceRefs: ref([22]),
      },
      {
        id: "exsig-q5-line-config",
        sourceQuestionNumber: 5,
        conceptIds: ["concept-point-to-point", "concept-multipoint"],
        skill: "identify",
        difficultySignal: "basic",
        claimClass: "DIRECT_SOURCE",
        sourceRefs: ref([22]),
      },
      {
        id: "exsig-q6-topo-line-config",
        sourceQuestionNumber: 6,
        conceptIds: ["concept-topology"],
        skill: "compare",
        distinctionTested: "topology by line configuration",
        difficultySignal: "intermediate",
        claimClass: "DIRECT_SOURCE",
        sourceRefs: ref([22]),
      },
      {
        id: "exsig-q8-topo-advantages",
        sourceQuestionNumber: 8,
        conceptIds: ["concept-mesh", "concept-star", "concept-bus", "concept-ring"],
        skill: "identify",
        difficultySignal: "intermediate",
        claimClass: "DIRECT_SOURCE",
        sourceRefs: ref([22]),
      },
      {
        id: "exsig-q9-link-counts",
        sourceQuestionNumber: 9,
        conceptIds: ["concept-mesh", "concept-star", "concept-bus", "concept-ring"],
        skill: "compute",
        formulaTested: "formula-mesh-links",
        difficultySignal: "intermediate",
        claimClass: "DIRECT_SOURCE",
        sourceRefs: ref([22], "For n devices... number of cable links required for a mesh, ring, bus, and star"),
      },
      {
        id: "exsig-q16-mesh-six",
        sourceQuestionNumber: 16,
        conceptIds: ["concept-mesh"],
        skill: "compute",
        formulaTested: "formula-mesh-links",
        difficultySignal: "basic",
        claimClass: "DIRECT_SOURCE",
        sourceRefs: ref([22]),
      },
      {
        id: "exsig-q17-failure-modes",
        sourceQuestionNumber: 17,
        conceptIds: ["concept-mesh", "concept-star", "concept-bus", "concept-ring"],
        skill: "analyze",
        distinctionTested: "failure consequences per topology",
        difficultySignal: "advanced",
        claimClass: "DIRECT_SOURCE",
        sourceRefs: ref([22]),
      },
    ],
    prerequisites: ["topic-networks-criteria", "topic-data-flow"],
    dependents: ["topic-network-categories", "topic-internetwork"],
    preservationRequirements: [
      "Point-to-point vs multipoint before topologies.",
      "All four basic topologies + hybrid with advantages/disadvantages/failure modes.",
      "Mesh formulas n(n−1)/2 and n−1 with conditions and n=6 example.",
      "Bus anatomy: drop line, tap, signal attenuation.",
      "Star hub single point of failure.",
    ],
    simplificationControl: {
      acceptable: ["Mesh is expensive but robust; star is cheap but hub-dependent."],
      notAcceptable: ["Saying mesh is always best; omitting bus/ring failure modes."],
    },
    evidenceQuality: "high",
    coverage: {
      definition: true,
      mechanism: true,
      relationships: true,
      examples: true,
      comparisons: true,
      formulas: true,
      confusions: true,
    },
    uncertainties: [],
  },
  {
    topicId: "topic-network-categories",
    title: "Categories of networks: LAN, WAN, MAN",
    importance: "core",
    sourceSection: "1.2 Categories of Networks",
    sourceRefs: ref([11, 12, 13], "A LAN normally covers an area less than 2 mi; a WAN can be worldwide."),
    learningObjectives: [
      "Classify networks by size into LAN, MAN, WAN",
      "Explain LAN resource sharing and typical topologies",
      "Distinguish switched WAN and point-to-point WAN",
      "Give MAN examples (DSL, cable TV)",
    ],
    concepts: [
      {
        id: "concept-lan",
        title: "LAN",
        meaning: "Usually privately owned; links devices in a single office, building, or campus; currently limited to a few kilometers.",
        explanation: {
          what: "Local area network for resource sharing.",
          how: "Share hardware/software/data among PCs/workstations; one machine may become server to clients.",
          parts: ["size", "transmission media", "topology"],
          concrete: "Home office of two PCs + printer, or company LAN with audio/video peripherals.",
          notMeaning: "Not defined primarily by brand of switch; size/ownership/scope matter.",
        },
        importance: "high",
        whyExamRelevant: "Exercise 18 classification; review Q10.",
        claimClass: C,
        sourceRefs: ref([11, 12], "A local area network (LAN) is usually privately owned"),
        prerequisites: ["concept-network", "concept-topology"],
        relatedConceptIds: ["concept-wan", "concept-man"],
        commonConfusionIds: ["conf-lan-wan-classify"],
      },
      {
        id: "concept-wan",
        title: "WAN",
        meaning: "Long-distance transmission of data/image/audio/video over large geographic areas (country, continent, world).",
        explanation: {
          what: "Wide area network spanning large regions.",
          parts: ["switched WAN", "point-to-point WAN"],
          concrete: "Internet backbones; dial-up home line to ISP.",
        },
        importance: "high",
        whyExamRelevant: "Core category; subtype distinction is exam-useful.",
        claimClass: C,
        sourceRefs: ref([12]),
        prerequisites: ["concept-network"],
        relatedConceptIds: ["concept-switched-wan", "concept-p2p-wan", "concept-lan"],
        commonConfusionIds: ["conf-lan-wan-classify"],
      },
      {
        id: "concept-switched-wan",
        title: "Switched WAN",
        meaning: "WAN connecting end systems, usually comprising a router connecting to another LAN or WAN.",
        explanation: {
          what: "Provider-operated switched network.",
          concrete: "Early X.25; Frame Relay replacement; ATM with fixed-size cells.",
        },
        importance: "medium",
        whyExamRelevant: "Distinction from p2p WAN.",
        claimClass: C,
        sourceRefs: ref([12, 13]),
        prerequisites: ["concept-wan"],
        relatedConceptIds: ["concept-p2p-wan"],
        commonConfusionIds: [],
      },
      {
        id: "concept-p2p-wan",
        title: "Point-to-point WAN",
        meaning: "Normally a leased line from telephone/cable provider connecting a home computer or small LAN to an ISP.",
        explanation: {
          what: "Leased access line.",
          concrete: "High-speed DSL or cable modem line.",
        },
        importance: "medium",
        whyExamRelevant: "Connects end-user edge to Internet access story.",
        claimClass: C,
        sourceRefs: ref([12, 13]),
        prerequisites: ["concept-wan"],
        relatedConceptIds: ["concept-switched-wan", "concept-isp-hierarchy"],
        commonConfusionIds: [],
      },
      {
        id: "concept-man",
        title: "MAN",
        meaning: "Network with size between LAN and WAN; normally covers a town or city; high-speed connectivity for endpoints across a city.",
        explanation: {
          what: "Metropolitan area network.",
          concrete: "Telephone company high-speed DSL to customer; cable TV network used for data.",
        },
        importance: "high",
        whyExamRelevant: "Middle category; often dropped when chapters only say LAN vs WAN.",
        claimClass: C,
        sourceRefs: ref([13], "A metropolitan area network (MAN) is a network with a size between a LAN and a WAN."),
        prerequisites: ["concept-lan", "concept-wan"],
        relatedConceptIds: ["concept-lan", "concept-wan"],
        commonConfusionIds: [],
      },
    ],
    relationships: [
      {
        id: "rel-size-spectrum",
        from: "concept-man",
        type: "special-case-of",
        to: "concept-network",
        explanation: "Category is determined primarily by size: LAN < MAN < WAN.",
        claimClass: C,
        sourceRefs: ref([11, 13]),
      },
      {
        id: "rel-lan-resources",
        from: "concept-lan",
        type: "enables",
        to: "concept-network",
        explanation: "LANs designed to share hardware, software, and data among workstations.",
        claimClass: C,
        sourceRefs: ref([12]),
      },
    ],
    definitions: [
      {
        id: "def-lan",
        term: "LAN",
        definition: "Local area network: privately owned, links devices in a single office/building/campus; currently limited to a few kilometers.",
        qualifier: "Distinguished by size, media, and topology",
        authoritative: true,
        claimClass: C,
        sourceRefs: ref([11, 12]),
      },
      {
        id: "def-wan",
        term: "WAN",
        definition: "Wide area network: long-distance transmission over large geographic areas.",
        authoritative: true,
        claimClass: C,
        sourceRefs: ref([12]),
      },
      {
        id: "def-man",
        term: "MAN",
        definition: "Metropolitan area network: size between LAN and WAN, covering a town or city.",
        authoritative: true,
        claimClass: C,
        sourceRefs: ref([13]),
      },
    ],
    formulas: [],
    examples: [
      {
        id: "ex-man-dsl-cable",
        title: "MAN via DSL or cable TV",
        conceptIds: ["concept-man"],
        scenario: "City-scale high-speed connectivity examples from the source.",
        inputs: ["telephone DSL line", "cable TV network upgraded for data"],
        reasoning: ["Endpoints spread over a city need more than a building LAN."],
        result: "MAN examples",
        lesson: "MAN is defined by geographic span, not a single technology.",
        claimClass: C,
        sourceRefs: ref([13]),
      },
      {
        id: "ex-home-hub-classify",
        title: "Home Ethernet hub classification",
        conceptIds: ["concept-lan"],
        scenario: "Exercise 18: two computers connected by an Ethernet hub at home.",
        inputs: ["two PCs", "Ethernet hub", "single home"],
        reasoning: ["Small privately owned local scope ⇒ LAN, not MAN/WAN."],
        result: "LAN",
        lesson: "Classify by size/ownership/scope.",
        claimClass: C,
        sourceRefs: ref([23]),
      },
    ],
    comparisons: [
      {
        id: "cmp-lan-man-wan",
        title: "LAN vs MAN vs WAN",
        items: ["LAN", "MAN", "WAN"],
        axes: [
          {
            axis: "geographic size",
            values: {
              LAN: "building/campus, a few km (source: often < 2 mi)",
              MAN: "town/city",
              WAN: "country/continent/world",
            },
          },
          {
            axis: "ownership",
            values: {
              LAN: "usually private",
              MAN: "often telco/cable provider",
              WAN: "service providers / backbones",
            },
          },
          {
            axis: "examples",
            values: {
              LAN: "office workgroup, home hub",
              MAN: "DSL city network, cable TV data",
              WAN: "Internet backbones, dial-up to ISP",
            },
          },
        ],
        similarities: ["All are networks of nodes and links."],
        commonTrap: "Inventing precise speed tables not present in this source.",
        claimClass: C,
        sourceRefs: ref([11, 12, 13]),
      },
      {
        id: "cmp-switched-vs-p2p-wan",
        title: "Switched WAN vs Point-to-point WAN",
        items: ["switched WAN", "point-to-point WAN"],
        axes: [
          {
            axis: "role",
            values: {
              "switched WAN": "connects end systems via routers; backbone-like",
              "point-to-point WAN": "leased line from home/small LAN to ISP",
            },
          },
          {
            axis: "examples",
            values: {
              "switched WAN": "X.25, Frame Relay, ATM",
              "point-to-point WAN": "DSL, cable modem line",
            },
          },
        ],
        claimClass: C,
        sourceRefs: ref([12, 13]),
      },
    ],
    applications: [],
    confusions: [
      {
        id: "conf-lan-wan-classify",
        left: "LAN",
        right: "MAN/WAN",
        whyConfused: "Marketing language and 'network' umbrella term.",
        correctDistinction: "Size/ownership/scope decide category; a home Ethernet hub is a LAN.",
        examTrap: "Choosing WAN because Ethernet sounds 'professional'.",
        sourceRelevance: "explicit",
        claimClass: C,
        sourceRefs: ref([23]),
      },
    ],
    exerciseSignals: [
      {
        id: "exsig-q10-lan-wan-factors",
        sourceQuestionNumber: 10,
        conceptIds: ["concept-lan", "concept-wan"],
        skill: "analyze",
        distinctionTested: "factors determining LAN vs WAN",
        difficultySignal: "intermediate",
        claimClass: "DIRECT_SOURCE",
        sourceRefs: ref([22]),
      },
      {
        id: "exsig-q18-home-lan",
        sourceQuestionNumber: 18,
        conceptIds: ["concept-lan"],
        skill: "apply",
        difficultySignal: "basic",
        claimClass: "DIRECT_SOURCE",
        sourceRefs: ref([23]),
      },
    ],
    prerequisites: ["topic-physical-structures"],
    dependents: ["topic-internetwork", "topic-internet"],
    preservationRequirements: [
      "LAN/MAN/WAN definitions by size/scope.",
      "Switched WAN vs point-to-point WAN.",
      "MAN examples DSL and cable TV.",
    ],
    simplificationControl: {
      acceptable: ["LAN is local and usually private; WAN spans large areas; MAN sits between."],
      notAcceptable: ["Invented Mbps comparison tables not in this source."],
    },
    evidenceQuality: "high",
    coverage: {
      definition: true,
      mechanism: true,
      relationships: true,
      examples: true,
      comparisons: true,
      formulas: false,
      confusions: true,
    },
    uncertainties: [],
  },
];
