import { ref, C, N } from "./helpers.mjs";

export const topicsD = [
  {
    topicId: "topic-internetwork",
    title: "Internetwork: connecting heterogeneous networks",
    importance: "core",
    sourceSection: "1.2 Interconnection of Networks",
    sourceRefs: ref([13, 14], "When two or more networks are connected, they become an internetwork, or internet."),
    learningObjectives: [
      "Define internetwork vs a single network",
      "Explain the two-LAN + WAN heterogeneous scenario",
      "Connect internetwork concept to the Internet",
    ],
    concepts: [
      {
        id: "concept-internetwork",
        title: "Internetwork / internet (lowercase)",
        meaning: "Two or more networks that can communicate with each other.",
        explanation: {
          what: "Network of networks at any scale.",
          why: "Rare to see LAN/MAN/WAN in isolation.",
          notMeaning: "Not automatically the global Internet (uppercase).",
        },
        importance: "high",
        whyExamRelevant: "Review Q11; bridge to section 1.3.",
        claimClass: C,
        sourceRefs: ref([13, 15], "An internet (note the lowercase letter i) is two or more networks that can communicate with each other."),
        prerequisites: ["concept-network", "concept-lan", "concept-wan"],
        relatedConceptIds: ["concept-internet-global", "concept-heterogeneous-mix"],
        commonConfusionIds: ["conf-network-vs-internet", "conf-internet-capitalization"],
      },
      {
        id: "concept-heterogeneous-mix",
        title: "Heterogeneous enterprise mix",
        meaning: "Different LAN topologies and WAN services joined into one internetwork.",
        explanation: {
          what: "Practical composition pattern.",
          how: "Lease switched WAN backbone; attach sites with point-to-point WANs.",
          concrete: "West bus LAN + east star LAN + president computer = 2 LANs + 4 WANs (Figure 1.12).",
        },
        importance: "high",
        whyExamRelevant: "Source's primary worked illustration of internetworking.",
        claimClass: C,
        sourceRefs: ref([13, 14]),
        prerequisites: ["concept-internetwork"],
        relatedConceptIds: ["concept-switched-wan", "concept-p2p-wan"],
        commonConfusionIds: [],
      },
    ],
    relationships: [
      {
        id: "rel-internet-is-notable-internetwork",
        from: "concept-internetwork",
        type: "special-case-of",
        to: "concept-internet-global",
        explanation: "The Internet is the most notable internetwork.",
        claimClass: C,
        sourceRefs: ref([15]),
      },
      {
        id: "rel-hetero-needs-wan",
        from: "concept-heterogeneous-mix",
        type: "depends-on",
        to: "concept-switched-wan",
        explanation: "Geographically separated LANs need WAN services to interconnect.",
        claimClass: C,
        sourceRefs: ref([13, 14]),
      },
    ],
    definitions: [
      {
        id: "def-internetwork",
        term: "Internetwork (internet)",
        definition: "Two or more networks that can communicate with each other.",
        qualifier: "Lowercase i in source terminology",
        authoritative: true,
        claimClass: C,
        sourceRefs: ref([15]),
      },
    ],
    formulas: [],
    examples: [
      {
        id: "ex-two-lan-wan",
        title: "East/west offices + president remote",
        conceptIds: ["concept-heterogeneous-mix"],
        scenario: "Organization with two offices and a remote president.",
        inputs: ["bus LAN (west)", "star LAN (east)", "president computer", "switched WAN", "three point-to-point WANs"],
        reasoning: [
          "Lease a switched WAN backbone from a provider.",
          "Connect each entity with a point-to-point WAN (DSL or cable modem).",
        ],
        result: "Heterogeneous network of four WANs and two LANs",
        lesson: "Internetworks compose different local designs via WAN services.",
        claimClass: C,
        sourceRefs: ref([13, 14], "Figure 1.12 A heterogeneous network made of four WANs and two LANs"),
      },
    ],
    comparisons: [
      {
        id: "cmp-network-vs-internetwork",
        title: "Network vs Internetwork",
        items: ["network", "internetwork"],
        axes: [
          {
            axis: "definition",
            values: {
              network: "devices connected by links",
              internetwork: "two or more interconnected networks",
            },
          },
        ],
        commonTrap: "Calling any single LAN an internet.",
        claimClass: C,
        sourceRefs: ref([5, 15]),
      },
    ],
    applications: [],
    confusions: [
      {
        id: "conf-network-vs-internet",
        left: "network",
        right: "Internet",
        whyConfused: "Colloquial use of 'the network' for the Internet.",
        correctDistinction: "Network = devices+links; Internet = huge collection of interconnected networks.",
        examTrap: "Defining Internet as 'a LAN with a router'.",
        sourceRelevance: "explicit",
        claimClass: C,
        sourceRefs: ref([15, 22]),
      },
    ],
    exerciseSignals: [
      {
        id: "exsig-q11-internet",
        sourceQuestionNumber: 11,
        conceptIds: ["concept-internetwork", "concept-internet-global"],
        skill: "define",
        distinctionTested: "internet vs Internet",
        difficultySignal: "basic",
        claimClass: "DIRECT_SOURCE",
        sourceRefs: ref([22], "What is an internet? What is the Internet?"),
      },
    ],
    prerequisites: ["topic-network-categories"],
    dependents: ["topic-internet"],
    preservationRequirements: [
      "Internetwork definition with lowercase-i distinction.",
      "Heterogeneous two-LAN + WAN scenario as the worked example.",
    ],
    simplificationControl: {
      acceptable: ["An internetwork is two or more connected networks."],
      notAcceptable: ["Equating every internetwork with the Internet."],
    },
    evidenceQuality: "high",
    coverage: {
      definition: true,
      mechanism: true,
      relationships: true,
      examples: true,
      comparisons: true,
      formulas: false,
      confusions: true,
    },
    uncertainties: [],
  },
  {
    topicId: "topic-internet",
    title: "The Internet: history and ISP hierarchy",
    importance: "core",
    sourceSection: "1.3 THE INTERNET",
    sourceRefs: ref([14, 15, 16, 17], "The Internet is a structured, organized system."),
    learningObjectives: [
      "Summarize ARPANET timeline 1960s–1973",
      "Explain TCP/IP split roles",
      "Describe four-level ISP hierarchy with NAP/peering",
    ],
    concepts: [
      {
        id: "concept-internet-global",
        title: "The Internet",
        meaning: "Uppercase-I Internet: collaboration of hundreds of thousands of interconnected networks.",
        explanation: {
          what: "Global internetwork used by individuals and organizations worldwide.",
          why: "Structured system, not a random mesh.",
          notMeaning: "Not government-run today (source: run by private companies).",
        },
        importance: "high",
        whyExamRelevant: "Core object of the chapter's third pillar.",
        claimClass: C,
        sourceRefs: ref([14, 15], "The most notable internet is called the Internet (uppercase letter I)"),
        prerequisites: ["concept-internetwork"],
        relatedConceptIds: ["concept-arpanet-history", "concept-isp-hierarchy"],
        commonConfusionIds: ["conf-internet-capitalization", "conf-network-vs-internet"],
      },
      {
        id: "concept-arpanet-history",
        title: "ARPANET history",
        meaning: "ARPA/DoD-funded path from isolated mainframes (mid-1960s) to a four-node ARPANET in 1969.",
        explanation: {
          what: "Origin story of the Internet.",
          how: "Hosts attach to IMPs; IMPs interconnect; NCP for host communication.",
          parts: ["ARPA/DoD motivation", "1967 ACM proposal", "1969 four nodes", "NCP", "1972 Internetting Project", "1973 TCP paper"],
          concrete: "Four nodes: UCLA, UCSB, SRI, University of Utah.",
        },
        importance: "high",
        whyExamRelevant: "Dense factual timeline; high MCQ potential; absent from sample chapter.",
        claimClass: C,
        sourceRefs: ref([15, 16]),
        prerequisites: ["concept-internet-global"],
        relatedConceptIds: ["concept-imp", "concept-tcp-ip-split"],
        commonConfusionIds: [],
      },
      {
        id: "concept-imp",
        title: "IMP (Interface Message Processor)",
        meaning: "Specialized computer attached to each host; IMPs connect to one another and to their hosts.",
        explanation: {
          what: "Early packet-switching node hardware concept.",
          why: "Allowed heterogeneous hosts to communicate via a common intermediate.",
        },
        importance: "medium",
        whyExamRelevant: "Supports ARPANET narrative.",
        claimClass: C,
        sourceRefs: ref([15], "attached to a specialized computer, called an interface message processor (IMP)"),
        prerequisites: ["concept-arpanet-history"],
        relatedConceptIds: ["concept-arpanet-history"],
        commonConfusionIds: [],
      },
      {
        id: "concept-tcp-ip-split",
        title: "TCP/IP split",
        meaning: "TCP split into Transmission Control Protocol and Internetworking Protocol (IP).",
        explanation: {
          what: "Division of labor in the protocol stack origin story.",
          how: "IP handles datagram routing; TCP handles segmentation, reassembly, error detection.",
          parts: ["encapsulation", "datagram", "gateway (1973 paper concepts)"],
        },
        importance: "high",
        whyExamRelevant: "Foundational protocol architecture fact.",
        claimClass: C,
        sourceRefs: ref([15], "IP would handle datagram routing while TCP would be responsible for higher-level functions"),
        prerequisites: ["concept-arpanet-history"],
        relatedConceptIds: ["concept-protocol-elements"],
        commonConfusionIds: [],
      },
      {
        id: "concept-isp-hierarchy",
        title: "ISP hierarchy",
        meaning: "International → national (backbones) → regional → local service providers.",
        explanation: {
          what: "Conceptual (not geographic) organization of today's Internet.",
          how: "Most end users connect via local ISPs; local connect to regional or national.",
          parts: ["international", "national", "regional", "local"],
          notMeaning: "Not a government hierarchy; private companies run it today.",
        },
        importance: "high",
        whyExamRelevant: "Structural knowledge for 'how the Internet is organized today'.",
        claimClass: C,
        sourceRefs: ref([16, 17], "There are international service providers, national service providers, regional service providers, and local service providers."),
        prerequisites: ["concept-internet-global"],
        relatedConceptIds: ["concept-nap-peering", "concept-p2p-wan"],
        commonConfusionIds: [],
      },
      {
        id: "concept-nap-peering",
        title: "NAPs and peering points",
        meaning: "NAPs are third-party complex switching stations connecting national backbones; peering points are private interconnects between national ISP networks.",
        explanation: {
          what: "Interconnection fabric among national backbones.",
          concrete: "Source states peering points normally operate up to 600 Mbps.",
        },
        importance: "medium",
        whyExamRelevant: "Detail supporting ISP hierarchy.",
        claimClass: C,
        sourceRefs: ref([16]),
        prerequisites: ["concept-isp-hierarchy"],
        relatedConceptIds: ["concept-isp-hierarchy"],
        commonConfusionIds: [],
      },
    ],
    relationships: [
      {
        id: "rel-ncp-precedes-tcpip",
        from: "concept-arpanet-history",
        type: "precedes",
        to: "concept-tcp-ip-split",
        explanation: "NCP provided early host communication; TCP/IP later replaced it.",
        claimClass: C,
        sourceRefs: ref([15, 16]),
      },
      {
        id: "rel-isp-part-of-internet",
        from: "concept-isp-hierarchy",
        type: "part-of",
        to: "concept-internet-global",
        explanation: "Today's Internet is organized via ISP layers and interconnects.",
        claimClass: C,
        sourceRefs: ref([16, 17]),
      },
    ],
    definitions: [
      {
        id: "def-internet",
        term: "The Internet",
        definition: "The most notable internetwork: a collaboration of hundreds of thousands of interconnected networks (uppercase I).",
        authoritative: true,
        claimClass: C,
        sourceRefs: ref([15]),
      },
      {
        id: "def-isp",
        term: "Internet service provider (ISP)",
        definition: "Organization providing Internet connectivity; may be international, national, regional, or local.",
        authoritative: true,
        claimClass: C,
        sourceRefs: ref([16, 17]),
      },
      {
        id: "def-nap",
        term: "Network access point (NAP)",
        definition: "Complex switching station (normally third-party) connecting national backbone ISPs.",
        authoritative: true,
        claimClass: C,
        sourceRefs: ref([16]),
      },
    ],
    formulas: [],
    examples: [
      {
        id: "ex-1969-four-nodes",
        title: "First ARPANET nodes (1969)",
        conceptIds: ["concept-arpanet-history"],
        scenario: "Operational ARPANET after 1967 proposal.",
        inputs: ["UCLA", "UCSB", "SRI", "University of Utah"],
        reasoning: ["Connect via IMPs; NCP for host-to-host communication."],
        result: "ARPANET reality with four nodes",
        lesson: "Internet began as a small research internetwork.",
        claimClass: C,
        sourceRefs: ref([15]),
      },
      {
        id: "ex-tcp-ip-roles",
        title: "TCP vs IP responsibilities",
        conceptIds: ["concept-tcp-ip-split"],
        scenario: "Post-split protocol design.",
        inputs: ["datagram routing need", "segmentation/reassembly/error detection need"],
        reasoning: ["IP: routing datagrams", "TCP: higher-level functions"],
        result: "TCP/IP pair",
        lesson: "Do not treat TCP and IP as synonyms.",
        claimClass: C,
        sourceRefs: ref([16]),
      },
    ],
    comparisons: [
      {
        id: "cmp-isp-levels",
        title: "International vs National vs Regional vs Local ISPs",
        items: ["international", "national", "regional", "local"],
        axes: [
          {
            axis: "role",
            values: {
              international: "connect nations together (top of hierarchy)",
              national: "backbone networks; NAPs/peering",
              regional: "smaller ISPs connected to national",
              local: "direct service to end users",
            },
          },
          {
            axis: "typical users",
            values: {
              international: "national ISPs",
              national: "regional ISPs / large customers",
              regional: "local ISPs",
              local: "home/business end users",
            },
          },
        ],
        claimClass: C,
        sourceRefs: ref([16, 17]),
      },
    ],
    applications: [],
    confusions: [
      {
        id: "conf-internet-capitalization",
        left: "internet (lowercase)",
        right: "Internet (uppercase)",
        whyConfused: "Same English word.",
        correctDistinction: "Lowercase = any internetwork; uppercase = the global Internet.",
        examTrap: "Using them interchangeably in definition questions.",
        sourceRelevance: "explicit",
        claimClass: C,
        sourceRefs: ref([15]),
      },
    ],
    exerciseSignals: [
      {
        id: "exsig-q11-internet-vs-internet",
        sourceQuestionNumber: 11,
        conceptIds: ["concept-internet-global", "concept-internetwork"],
        skill: "define",
        difficultySignal: "basic",
        claimClass: "DIRECT_SOURCE",
        sourceRefs: ref([22]),
      },
      {
        id: "exsig-q25-phone-vs-internet",
        sourceQuestionNumber: 25,
        conceptIds: ["concept-internet-global"],
        skill: "compare",
        difficultySignal: "intermediate",
        claimClass: "DIRECT_SOURCE",
        sourceRefs: ref([23], "Compare the telephone network and the Internet."),
      },
    ],
    prerequisites: ["topic-internetwork"],
    dependents: ["topic-protocols", "topic-standards"],
    preservationRequirements: [
      "1960s–1973 timeline: ARPA, ARPANET, IMP, NCP, Cerf/Kahn, TCP/IP split with roles.",
      "Four-level ISP hierarchy + NAP/peering.",
      "Uppercase Internet vs lowercase internet.",
    ],
    simplificationControl: {
      acceptable: ["IP routes datagrams; TCP handles segmentation/reassembly/errors."],
      notAcceptable: ["Skipping history entirely; saying the Internet is 'just a big LAN'."],
    },
    evidenceQuality: "high",
    coverage: {
      definition: true,
      mechanism: true,
      relationships: true,
      examples: true,
      comparisons: true,
      formulas: false,
      confusions: true,
    },
    uncertainties: [],
  },
  {
    topicId: "topic-protocols",
    title: "Protocols: syntax, semantics, timing",
    importance: "core",
    sourceSection: "1.4 Protocols",
    sourceRefs: ref([17], "The key elements of a protocol are syntax, semantics, and timing."),
    learningObjectives: [
      "Define protocol with three key elements",
      "Explain syntax, semantics, timing separately",
      "Use the rate-mismatch example for timing",
    ],
    concepts: [
      {
        id: "concept-protocol-elements",
        title: "Protocol key elements",
        meaning: "Syntax, semantics, and timing.",
        explanation: {
          what: "Complete triad defining a protocol.",
          why: "Rules must specify structure, meaning, and temporal behavior.",
          parts: ["syntax", "semantics", "timing"],
        },
        importance: "high",
        whyExamRelevant: "Review Q12; core definition depth beyond 'rules'.",
        claimClass: C,
        sourceRefs: ref([17]),
        prerequisites: ["concept-protocol-basic"],
        relatedConceptIds: ["concept-syntax", "concept-semantics", "concept-timing"],
        commonConfusionIds: ["conf-protocol-standard"],
      },
      {
        id: "concept-entity",
        title: "Entity",
        meaning: "Anything capable of sending or receiving information.",
        explanation: {
          what: "Communication endpoint abstraction in systems.",
        },
        importance: "medium",
        whyExamRelevant: "Vocabulary for protocol discussion.",
        claimClass: C,
        sourceRefs: ref([17]),
        prerequisites: [],
        relatedConceptIds: ["concept-protocol-elements"],
        commonConfusionIds: [],
      },
      {
        id: "concept-syntax",
        title: "Syntax",
        meaning: "Structure or format of the data — the order in which data are presented.",
        explanation: {
          what: "Bit-layout rules.",
          concrete: "First 8 bits sender address, second 8 bits receiver address, rest message.",
        },
        importance: "high",
        whyExamRelevant: "One of three exam-asked elements.",
        claimClass: C,
        sourceRefs: ref([17], "The term syntax refers to the structure or format of the data"),
        prerequisites: ["concept-protocol-elements"],
        relatedConceptIds: ["concept-semantics", "concept-timing"],
        commonConfusionIds: [],
      },
      {
        id: "concept-semantics",
        title: "Semantics",
        meaning: "Meaning of each section of bits and the action to take based on that interpretation.",
        explanation: {
          what: "Interpretation rules.",
          concrete: "Does an address identify the route or the final destination?",
        },
        importance: "high",
        whyExamRelevant: "One of three elements; often confused with syntax.",
        claimClass: C,
        sourceRefs: ref([17]),
        prerequisites: ["concept-protocol-elements"],
        relatedConceptIds: ["concept-syntax"],
        commonConfusionIds: [],
      },
      {
        id: "concept-timing",
        title: "Timing",
        meaning: "When data should be sent and how fast they can be sent.",
        explanation: {
          what: "Temporal constraints including rate matching.",
          whenChanges: "Sender faster than receiver ⇒ overload and data loss risk.",
          concrete: "Sender 100 Mbps vs receiver 1 Mbps.",
        },
        importance: "high",
        whyExamRelevant: "Third element; concrete rate example.",
        claimClass: C,
        sourceRefs: ref([17]),
        prerequisites: ["concept-protocol-elements"],
        relatedConceptIds: ["concept-syntax", "concept-semantics"],
        commonConfusionIds: [],
      },
    ],
    relationships: [
      {
        id: "rel-protocol-triad",
        from: "concept-syntax",
        type: "part-of",
        to: "concept-protocol-elements",
        explanation: "Syntax + semantics + timing together define what/how/when to communicate.",
        claimClass: C,
        sourceRefs: ref([17]),
      },
      {
        id: "rel-protocol-vs-standard",
        from: "concept-protocol-elements",
        type: "differs-from",
        to: "concept-standards-need",
        explanation: "Protocol = rules; standard = agreed-upon rules for interoperability.",
        claimClass: C,
        sourceRefs: ref([17, 18]),
      },
    ],
    definitions: [
      {
        id: "def-protocol-full",
        term: "Protocol (full)",
        definition: "Set of rules governing data communication; defines what is communicated, how, and when. Key elements: syntax, semantics, timing.",
        authoritative: true,
        claimClass: C,
        sourceRefs: ref([17]),
      },
    ],
    formulas: [],
    examples: [
      {
        id: "ex-timing-mismatch",
        title: "100 Mbps sender vs 1 Mbps receiver",
        conceptIds: ["concept-timing"],
        scenario: "Rate mismatch between communicating entities.",
        inputs: ["sender produces at 100 Mbps", "receiver processes at 1 Mbps"],
        reasoning: ["Production rate far exceeds processing rate."],
        result: "Transmission overloads the receiver; some data lost",
        lesson: "Protocols must address timing/rate, not only format.",
        claimClass: C,
        sourceRefs: ref([17]),
      },
      {
        id: "ex-syntax-header",
        title: "Simple header layout",
        conceptIds: ["concept-syntax"],
        scenario: "Illustrative protocol field order.",
        inputs: ["first 8 bits sender address", "second 8 bits receiver address", "remainder = message"],
        reasoning: ["Syntax specifies presentation order of fields."],
        result: "Parseable frame structure",
        lesson: "Syntax is about structure/order of bits.",
        claimClass: C,
        sourceRefs: ref([17]),
      },
    ],
    comparisons: [
      {
        id: "cmp-protocol-elements",
        title: "Syntax vs Semantics vs Timing",
        items: ["syntax", "semantics", "timing"],
        axes: [
          {
            axis: "question answered",
            values: {
              syntax: "What is the structure/format?",
              semantics: "What does it mean / what action?",
              timing: "When and how fast?",
            },
          },
          {
            axis: "source example",
            values: {
              syntax: "8+8 bit address header",
              semantics: "route vs destination address",
              timing: "100 Mbps sender vs 1 Mbps receiver",
            },
          },
        ],
        commonTrap: "Calling semantics 'grammar' or syntax 'meaning'.",
        claimClass: C,
        sourceRefs: ref([17]),
      },
    ],
    applications: [],
    confusions: [
      {
        id: "conf-protocol-standard",
        left: "protocol",
        right: "standard",
        whyConfused: "Both are 'rules' in casual speech.",
        correctDistinction: "Protocol governs communication; standard is an agreed-upon rule ensuring interoperation across manufacturers.",
        examTrap: "Defining protocol as 'a document approved by ISO'.",
        sourceRelevance: "explicit",
        claimClass: C,
        sourceRefs: ref([17, 18]),
      },
    ],
    exerciseSignals: [
      {
        id: "exsig-q12-why-protocols",
        sourceQuestionNumber: 12,
        conceptIds: ["concept-protocol-elements"],
        skill: "define",
        difficultySignal: "basic",
        claimClass: "DIRECT_SOURCE",
        sourceRefs: ref([22], "Why are protocols needed?"),
      },
    ],
    prerequisites: ["topic-data-communication", "topic-internet"],
    dependents: ["topic-standards"],
    preservationRequirements: [
      "Always teach syntax/semantics/timing together.",
      "Rate-mismatch timing example.",
      "Protocol vs standard distinction preview.",
    ],
    simplificationControl: {
      acceptable: ["Protocol = what, how, when."],
      notAcceptable: ["Protocol = just 'a set of rules' without the three elements."],
    },
    evidenceQuality: "high",
    coverage: {
      definition: true,
      mechanism: true,
      relationships: true,
      examples: true,
      comparisons: true,
      formulas: false,
      confusions: true,
    },
    uncertainties: [],
  },
  {
    topicId: "topic-standards",
    title: "Standards, organizations, forums, Internet standards",
    importance: "core",
    sourceSection: "1.4 PROTOCOLS AND STANDARDS",
    sourceRefs: ref([18, 19], "Data communication standards fall into two categories: de facto and de jure."),
    learningObjectives: [
      "Explain why standards are needed",
      "Distinguish de facto and de jure",
      "Name major standards organizations",
      "Describe draft → RFC → Internet standard process",
    ],
    concepts: [
      {
        id: "concept-standards-need",
        title: "Why standards are needed",
        meaning: "To ensure products from different manufacturers work together as expected.",
        explanation: {
          what: "Interoperability requirement in a heterogeneous vendor market.",
          why: "Without standards, vendor products cannot reliably interconnect.",
        },
        importance: "high",
        whyExamRelevant: "Review Q13.",
        claimClass: C,
        sourceRefs: ref([18, 22]),
        prerequisites: ["concept-protocol-elements"],
        relatedConceptIds: ["concept-de-facto", "concept-de-jure"],
        commonConfusionIds: ["conf-protocol-standard"],
      },
      {
        id: "concept-de-facto",
        title: "De facto standards",
        meaning: "Standards not approved by an organized body but adopted through widespread use.",
        explanation: {
          what: "By fact / by convention.",
          how: "Often established originally by manufacturers defining new product functionality.",
        },
        importance: "high",
        whyExamRelevant: "Paired classification with de jure.",
        claimClass: C,
        sourceRefs: ref([18], "De facto. Standards that have not been approved by an organized body"),
        prerequisites: ["concept-standards-need"],
        relatedConceptIds: ["concept-de-jure"],
        commonConfusionIds: [],
      },
      {
        id: "concept-de-jure",
        title: "De jure standards",
        meaning: "Standards legislated by an officially recognized body.",
        explanation: {
          what: "By law / by regulation.",
        },
        importance: "high",
        whyExamRelevant: "Paired classification with de facto.",
        claimClass: C,
        sourceRefs: ref([18]),
        prerequisites: ["concept-standards-need"],
        relatedConceptIds: ["concept-de-facto"],
        commonConfusionIds: [],
      },
      {
        id: "concept-standards-orgs",
        title: "Standards organizations",
        meaning: "ISO, ITU-T (formerly CCITT), ANSI, IEEE, EIA; plus forums and regulatory agencies such as FCC.",
        explanation: {
          what: "Bodies that create or influence standards.",
          parts: ["ISO", "ITU-T", "ANSI", "IEEE", "EIA", "forums", "FCC"],
          concrete: "ITU-T name change from CCITT on March 1, 1993; ANSI is private nonprofit, not US federal.",
        },
        importance: "high",
        whyExamRelevant: "Factual MCQs on org roles; key-terms list includes them.",
        claimClass: C,
        sourceRefs: ref([18, 19]),
        prerequisites: ["concept-standards-need"],
        relatedConceptIds: ["concept-forums", "concept-rfc"],
        commonConfusionIds: [],
      },
      {
        id: "concept-forums",
        title: "Forums",
        meaning: "Special-interest groups of corporate representatives that evaluate and help standardize technologies faster than formal committees.",
        explanation: {
          what: "Acceleration layer for emerging tech.",
          how: "Work with universities/users; present conclusions to standards bodies.",
        },
        importance: "medium",
        whyExamRelevant: "Distinguishes forums from formal committees.",
        claimClass: C,
        sourceRefs: ref([19]),
        prerequisites: ["concept-standards-orgs"],
        relatedConceptIds: ["concept-standards-orgs"],
        commonConfusionIds: [],
      },
      {
        id: "concept-rfc",
        title: "RFC and Internet standard process",
        meaning: "Internet draft (working document, no official status, 6-month lifetime) may become a Request for Comment; RFCs have maturity levels and requirement categories.",
        explanation: {
          what: "Internet standards pipeline.",
          how: "Draft → RFC (edited, numbered, published) → maturity levels.",
          notMeaning: "RFC does not automatically mean full Internet standard.",
        },
        importance: "high",
        whyExamRelevant: "Process knowledge; key term in glossary.",
        claimClass: C,
        sourceRefs: ref([19], "An Internet draft is a working document... a 6-month lifetime."),
        prerequisites: ["concept-standards-need"],
        relatedConceptIds: ["concept-standards-orgs"],
        commonConfusionIds: [],
      },
    ],
    relationships: [
      {
        id: "rel-draft-to-rfc",
        from: "concept-rfc",
        type: "precedes",
        to: "concept-standards-need",
        explanation: "Specification begins as draft, may become RFC, then Internet standard.",
        claimClass: C,
        sourceRefs: ref([19]),
      },
      {
        id: "rel-forums-to-bodies",
        from: "concept-forums",
        type: "enables",
        to: "concept-standards-orgs",
        explanation: "Forums speed evaluation and present conclusions to formal standards bodies.",
        claimClass: C,
        sourceRefs: ref([19]),
      },
    ],
    definitions: [
      {
        id: "def-de-facto",
        term: "De facto standard",
        definition: "Standard established by widespread use rather than approval by an organized body.",
        authoritative: true,
        claimClass: C,
        sourceRefs: ref([18]),
      },
      {
        id: "def-de-jure",
        term: "De jure standard",
        definition: "Standard legislated by an officially recognized body.",
        authoritative: true,
        claimClass: C,
        sourceRefs: ref([18]),
      },
      {
        id: "def-rfc",
        term: "Request for Comment (RFC)",
        definition: "Published specification in the Internet standards process; idea/concept precursor to an Internet standard.",
        qualifier: "Goes through maturity levels and requirement categories",
        authoritative: true,
        claimClass: C,
        sourceRefs: ref([19]),
      },
    ],
    formulas: [],
    examples: [],
    comparisons: [
      {
        id: "cmp-de-facto-de-jure",
        title: "De facto vs De jure",
        items: ["de facto", "de jure"],
        axes: [
          {
            axis: "approval",
            values: {
              "de facto": "not approved by organized body",
              "de jure": "legislated by recognized body",
            },
          },
          {
            axis: "origin",
            values: {
              "de facto": "widespread use / manufacturers",
              "de jure": "official standards process",
            },
          },
        ],
        commonTrap: "Calling a popular product feature automatically de jure.",
        claimClass: C,
        sourceRefs: ref([18]),
      },
      {
        id: "cmp-protocol-vs-standard",
        title: "Protocol vs Standard",
        items: ["protocol", "standard"],
        axes: [
          {
            axis: "meaning",
            values: {
              protocol: "rules governing data communication",
              standard: "agreed-upon rules ensuring interoperation",
            },
          },
        ],
        claimClass: C,
        sourceRefs: ref([17, 18]),
      },
      {
        id: "cmp-forum-vs-committee",
        title: "Forum vs Standards committee",
        items: ["forum", "standards creation committee"],
        axes: [
          {
            axis: "speed/process",
            values: {
              forum: "faster special-interest evaluation",
              "standards creation committee": "procedural, slower, formal ratification",
            },
          },
        ],
        claimClass: C,
        sourceRefs: ref([19]),
      },
    ],
    applications: [],
    confusions: [
      {
        id: "conf-protocol-standard-2",
        left: "protocol",
        right: "standard",
        whyConfused: "Overlapping rule language.",
        correctDistinction: "Protocol is the communication ruleset; standard is the agreed/recognized specification enabling multi-vendor interoperation.",
        examTrap: "Using the terms as perfect synonyms.",
        sourceRelevance: "explicit",
        claimClass: C,
        sourceRefs: ref([17, 18]),
      },
    ],
    exerciseSignals: [
      {
        id: "exsig-q13-why-standards",
        sourceQuestionNumber: 13,
        conceptIds: ["concept-standards-need"],
        skill: "define",
        difficultySignal: "basic",
        claimClass: "DIRECT_SOURCE",
        sourceRefs: ref([22], "Why are standards needed?"),
      },
      {
        id: "exsig-q29-ietf-rfc",
        sourceQuestionNumber: 29,
        conceptIds: ["concept-rfc"],
        skill: "analyze",
        difficultySignal: "intermediate",
        claimClass: "DIRECT_SOURCE",
        sourceRefs: ref([23], "discuss the different types of RFCs"),
      },
    ],
    prerequisites: ["topic-protocols"],
    dependents: [],
    preservationRequirements: [
      "De facto vs de jure with definitions.",
      "Major orgs ISO, ITU-T, ANSI, IEEE, EIA (+ FCC regulatory).",
      "Draft → RFC → Internet standard process with 6-month draft lifetime.",
      "Forums as accelerators, not replacements for committees.",
    ],
    simplificationControl: {
      acceptable: ["De facto = by use; de jure = by official body."],
      notAcceptable: ["Saying all Internet standards are de jure laws."],
    },
    evidenceQuality: "high",
    coverage: {
      definition: true,
      mechanism: true,
      relationships: true,
      examples: false,
      comparisons: true,
      formulas: false,
      confusions: true,
    },
    uncertainties: [],
  },
];

export const externalUnverifiedMaterial = [
  {
    id: "extra-shannon",
    title: "Shannon capacity formula and numeric Shannon examples",
    presentInSample: true,
    claimClass: "EXTERNAL_CONTEXT",
    note: "Not in the attached 23-page Ch.1 source. Treat as enrichment only after source-backed topics; requires another verified source to become DIRECT_SOURCE.",
    sourceRefs: [],
  },
  {
    id: "extra-snr-db",
    title: "SNR in dB formula",
    presentInSample: true,
    claimClass: "EXTERNAL_CONTEXT",
    note: "Not in attached source.",
    sourceRefs: [],
  },
  {
    id: "extra-transmission-time",
    title: "T = L/B and 10 MB / 20 Mbps worked example",
    presentInSample: true,
    claimClass: "EXTERNAL_CONTEXT",
    note: "Not in attached source.",
    sourceRefs: [],
  },
  {
    id: "extra-ipconfig",
    title: "Windows ipconfig practical lab",
    presentInSample: true,
    claimClass: "EXTERNAL_CONTEXT",
    note: "Sample-only application block; not in attached source.",
    sourceRefs: [],
  },
  {
    id: "extra-mb-mb-trap",
    title: "MB vs Mb exam trap emphasis",
    presentInSample: true,
    claimClass: "EXTERNAL_CONTEXT",
    note: "Common industry trap but not stated in this Ch.1 extract.",
    sourceRefs: [],
  },
  {
    id: "extra-bandwidth-definition",
    title: "Bandwidth definition card",
    presentInSample: true,
    claimClass: "EXTERNAL_CONTEXT",
    note: "Not defined in attached Ch.1; sample invents a Bandwidth definition.",
    sourceRefs: [],
  },
];

export const crossTopicFlags = [
  {
    id: "flag-bandwidth-absent",
    severity: "info",
    message: "Sample chapter teaches Bandwidth; Forouzan Ch.1 extract teaches throughput/delay. CGP-2 should decide whether Bandwidth stays as EXTERNAL_CONTEXT enrichment.",
    relatedTopicIds: ["topic-networks-criteria"],
  },
  {
    id: "flag-unicode-bits",
    severity: "review",
    message: "Source states Unicode uses 32 bits. Modern encodings differ. Preserve as DIRECT_SOURCE claim of this textbook; optional EXTERNAL_CONTEXT note may be added in composition with explicit marking.",
    relatedTopicIds: ["topic-data-representation"],
  },
  {
    id: "flag-sample-shannon-displaces-source",
    severity: "review",
    message: "Current sample over-weights Shannon/SNR/T=L/B (not in this source) while omitting topology, Internet history, and standards. CGP-2 coverage validation must not treat sample completeness as source completeness.",
    relatedTopicIds: [
      "topic-physical-structures",
      "topic-internet",
      "topic-standards",
      "topic-networks-criteria",
    ],
  },
];
